Description ????????????????????????

In [1]:
import numpy as np
import cv2 as cv
import yaml
from pathlib import Path
import sys
import pandas as pd

In [ ]:
LCL_PATH = str(Path().cwd())
LCL_PATH

'c:\\Users\\Matei\\MLProjects\\UAIC-MIAO1\\Sem-1\\Metode-inspirate-din-natura\\Homeworks\\MIN\\laborator_1\\TTP'

In [ ]:

# adding local_folder to the system path
sys.path.append(LCL_PATH)
sys.path.append("/home/gheorghe/Desktop/AI/manager/imshow")

def remove_modules(modules_name, *arg):
    if (modules_name in sys.modules):
        del sys.modules[modules_name]
        for key in arg:
            tmp_modules = "{}.{}".format(modules_name, key)
            del sys.modules[tmp_modules]

In [ ]:

remove_modules("builds.ttp_generator")
remove_modules("builds.genetic_optimizer_TTP")
remove_modules("builds.test_genetic_optimizer_TTP")

from builds.ttp_generator import *
from builds.test_genetic_optimizer_TTP import *
from builds.genetic_optimizer_TTP import *

# Test methods GA

### init

In [ ]:
# creează obiectul GA
ga = GeneticAOTSP()

# creează tester
tester = TestGaoTTP(ga)

# rulează testul nou
tester.initPopulation()

print("=== TOTUL OK ===")

In [30]:
map_generator = TTPGenerator(nbr_city=9, max_distance=300)
map_of_distance = map_generator()
map_of_distance

array([[  0.        , 225.        , 184.04890654, 184.62123388,
        149.24141516, 101.01980004, 105.38026381,  83.00602388,
        167.58579892],
       [225.        ,   0.        , 129.34063553, 216.17122843,
        248.65236777, 248.45522735, 165.92166827, 296.0827587 ,
         91.26883367],
       [184.04890654, 129.34063553,   0.        ,  88.27797007,
        282.63934616, 257.00778198,  81.49233093, 224.89108475,
         45.96737974],
       [184.62123388, 216.17122843,  88.27797007,   0.        ,
        317.08989262, 278.91934318,  91.58602513, 190.24457942,
        126.49110641],
       [149.24141516, 248.65236777, 282.63934616, 317.08989262,
          0.        ,  53.31041174, 226.11943747, 216.52944373,
        245.7356303 ],
       [101.01980004, 248.45522735, 257.00778198, 278.91934318,
         53.31041174,   0.        , 190.68298298, 163.47782724,
        226.        ],
       [105.38026381, 165.92166827,  81.49233093,  91.58602513,
        226.11943747, 190.6829

In [31]:
tsp = TSP()
tsp.setParameters(
    POPULATION_SIZE = 20,  # numarul populatiei
    MUTATION_RATE   = 0.01,   # threshold-ul pentru a face o mutatie genetica
    CROSSOVER_RATE  = 0.5,   # threshold-ul pentru incrucisarea parintilor
    SELECT_RATE     = 0.7,   # threshold-ul de selectie, selectare dupa compatibilitate sau dupa probabilitate
    K_DISTANCE      = 1.0,   # coeficientul de inhibare a distantei
    K_NBR_CITY      = 0.9,   # coeficientul de inhibare a numarului de orase
    GENERATIONS     = 100,   # numarul de generatii
    K_BEST          = 15,     # salveaza pentru urmatoarea generatie numarul de indivizi, cu cel mai mare scor
    K_WRONG         = 5,     # salveaza pentru urmatoarea generatie numarul de indivizi, cu cel mai mic scor
    )
tsp.setMap(map_of_distance)
test_tsp = TestTSP(tsp)

NameError: name 'TSP' is not defined

### test

In [ ]:
test_tsp.initPopulation()

+++start
result [[7 1 8 3 5 2 6 4 0 7]
 [1 0 5 8 7 4 2 3 6 1]
 [7 2 5 8 3 4 0 1 6 7]
 [7 3 5 0 8 2 4 6 1 7]
 [1 7 2 5 6 8 3 4 0 1]
 [7 5 6 8 3 0 4 2 1 7]
 [0 3 1 7 4 8 5 6 2 0]
 [7 6 5 3 4 8 1 2 0 7]
 [3 6 1 7 4 2 5 0 8 3]
 [0 6 5 8 2 7 1 4 3 0]
 [3 2 8 6 0 7 5 1 4 3]
 [6 0 3 2 5 7 8 1 4 6]
 [6 2 0 5 7 1 4 3 8 6]
 [6 8 4 5 7 3 2 0 1 6]
 [2 1 3 7 4 8 5 6 0 2]
 [5 3 4 2 1 0 6 7 8 5]
 [5 3 8 6 2 4 0 7 1 5]
 [7 3 0 8 4 6 5 1 2 7]
 [2 0 4 1 6 5 8 7 3 2]
 [0 2 1 6 7 4 5 8 3 0]]


In [ ]:
test_tsp.selectValidPopulation()

arg_parents1 [ 1 12 19 18  3]
fitness_values_parents1 [0.35257614 0.78126312 0.17107191 0.24514469 0.07050225]
result [ 0  2  4  5  6  7  8  9 10 11 13 14 15 16 17 18]


In [ ]:
test_tsp.selectParent1()

fitness_values [0.81587703 0.89667345 0.40184088 0.78983545 0.156792   0.15029457
 0.41311903 0.27048943 0.05163992 0.30459938 0.49216869 0.64966057
 0.91074404 0.00253847 0.47738502 0.05540931 0.31771491 0.78938948
 0.90242842 0.28934634]
fitness_values [13  8 15  5  4  7 19  9 16  2  6 14 10 11 17  3  0  1 18 12]
result [0.81587703 0.89667345 0.40184088 0.78983545 0.156792   0.15029457
 0.41311903 0.27048943 0.05163992 0.30459938 0.49216869 0.64966057
 0.91074404 0.00253847 0.47738502 0.05540931 0.31771491 0.78938948
 0.90242842 0.28934634]


In [ ]:
test_tsp.selectParent2()

fitness_values [0.60508195 0.10749925 0.2971688  0.93634787 0.53821027 0.46006785
 0.30967343 0.15591332 0.11117717 0.18642779 0.89732319 0.04274872
 0.87585003 0.00155572 0.95438546 0.680973   0.25113319 0.31277229
 0.77781062 0.63518519]
argsort fitness_values [13 11  1  8  7  9 16  2  6 17  5  4  0 19 15 18 12 10  3 14]
fitness_partener 0.4874895934049823
result [16  2 15 14  4]
result [17 17 17 19 18]
result [ 7  2 18 17 10]
result [ 4 15  6 19 14]
result [18 18 18 18 14]
result [15 15  4 19 18]
result [12  5  5 13 10]
result [10  3  6  3 19]
result [ 8 17 16  2 12]
result [ 3 12 14 18  1]
result [12 15 14  0 13]
result [ 0 14 19 19 18]
result [14 18  3  0 13]
result [ 0 15 18 14  8]
result [15 14 18 10 19]
result [14 14  9 12 19]
result [19  2 12  2 18]
result [ 3 12  6 18 19]
result [18  4 19 14 19]
result [ 3 19 19 17 15]


In [ ]:
test_tsp.crossover()

parent1 [8 7 2 4 1 0 5 6 3 8]
parent2 [4 3 0 7 6 2 1 8 5 4]
childs [[8 7 2 4 1 2 1 8 5 8]
 [4 3 0 7 6 0 5 6 3 4]
 [4 3 0 7 6 0 5 6 3 4]
 [4 7 2 4 1 2 1 8 5 4]
 [8 7 2 4 1 0 5 6 3 8]]
childs [[4 7 2 4 1 2 1 8 5 4]
 [4 7 2 4 1 2 1 8 5 4]
 [8 3 0 7 6 2 5 6 3 8]
 [4 3 0 7 6 0 5 6 3 4]
 [4 3 0 7 6 0 5 6 3 4]]
childs [[4 3 0 7 6 2 1 6 3 4]
 [4 7 2 4 1 2 1 8 5 4]
 [4 7 2 4 1 0 5 6 3 4]
 [8 3 0 7 6 0 5 6 3 8]
 [8 3 2 4 6 0 1 8 3 8]]
childs [[8 3 2 4 6 0 1 8 3 8]
 [4 7 2 4 1 2 1 8 5 4]
 [4 3 2 4 1 0 5 6 3 4]
 [4 3 0 7 6 0 5 6 3 4]
 [4 3 0 4 6 2 5 8 5 4]]
childs [[8 3 0 7 6 0 5 6 3 8]
 [4 3 2 4 1 0 5 6 3 4]
 [8 7 0 7 6 2 5 6 3 8]
 [8 7 2 4 1 2 1 8 5 8]
 [4 7 2 4 1 2 1 8 5 4]]
childs [[4 7 2 4 1 0 5 8 5 4]
 [4 3 0 4 1 2 1 8 5 4]
 [4 3 0 7 6 0 5 6 3 4]
 [4 3 2 4 1 0 5 6 3 4]
 [4 7 2 4 1 2 1 8 5 4]]
childs [[8 7 2 4 1 2 1 6 3 8]
 [4 3 0 7 6 0 5 6 3 4]
 [8 3 0 7 6 0 5 6 3 8]
 [4 3 0 4 1 0 5 8 5 4]
 [4 3 0 4 1 2 1 8 3 4]]
childs [[4 7 2 4 1 2 1 8 5 4]
 [8 7 2 4 1 2 1 8 5 8]
 [8 7 0 4 1 0 1 8 3 8]
 [4

In [ ]:
test_tsp.mutate()

parent1 [6 1 4 0 5 2 7 8 3 6]
parent2 [2 3 1 0 6 8 7 5 4 2]
Operatia de mutatie a fost aplicata: [[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False  True False False False False  True]
 [False False False False False False False  True False  True]
 [False False False False False False False False False False]]
Operatia de mutatie a fost aplicata: [[False False False False False False False False False False]
 [False False False False  True False  True False False False]
 [False  True False False False False False False False  True]
 [False False False False False False False False False False]
 [False False  True False False False False False False False]]
Operatia de mutatie a fost aplicata: [[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False 

In [ ]:
test_tsp.getIndividDistance()

individ [2 8 3 7 6 0 1 5 4 2]
distance 1202.7363897842674


In [ ]:
test_tsp.getIndividNumberCities()

individ [6 4 0 7 5 3 1 2 8 6]
number_city 9


In [ ]:
test_tsp.getDistances()

population [[7 3 1 4 0 6 2 5 8 7]
 [5 8 7 3 4 0 1 2 6 5]
 [5 2 4 8 3 7 6 0 1 5]
 [4 5 3 6 8 1 0 7 2 4]
 [8 4 2 7 3 5 6 0 1 8]
 [3 6 8 2 5 0 7 1 4 3]
 [0 6 3 4 2 5 7 8 1 0]
 [4 2 7 6 0 3 5 8 1 4]
 [7 0 6 8 4 3 5 1 2 7]
 [5 2 1 6 8 0 3 7 4 5]
 [1 7 2 4 5 0 6 3 8 1]
 [1 6 8 7 4 3 2 5 0 1]
 [7 3 6 0 5 1 4 2 8 7]
 [5 7 0 2 1 3 4 8 6 5]
 [7 6 1 2 4 5 0 8 3 7]
 [0 3 7 4 6 8 2 1 5 0]
 [1 6 7 0 5 8 3 4 2 1]
 [2 4 6 3 7 1 0 8 5 2]
 [8 2 3 0 7 5 1 6 4 8]
 [1 6 3 7 8 4 2 0 5 1]]
distances [1268.63196043 1451.60715666 1188.13886801 1098.33747194 1110.83786565
 1213.81242964 1352.00091418  926.06924805  949.52084159 1245.0234691
 1273.32344917 1281.50135326 1046.99302559 1289.84728983 1337.15061962
  971.76373889 1361.50177019 1423.68037773 1104.79849729 1146.79785489]


In [ ]:
test_tsp.getNumberCities()

population [[2 6 8 1 7 4 0 5 3 2]
 [6 5 7 2 1 4 3 8 0 6]
 [0 5 1 8 4 3 6 2 7 0]
 [4 1 6 7 0 5 8 2 3 4]
 [7 8 2 1 0 5 6 3 4 7]
 [1 3 7 2 5 0 8 4 6 1]
 [3 2 7 6 4 1 5 0 8 3]
 [7 8 1 4 6 2 5 0 3 7]
 [0 6 5 3 1 7 4 8 2 0]
 [0 8 6 5 4 2 1 3 7 0]
 [0 5 3 2 1 7 6 8 4 0]
 [5 1 8 6 3 4 0 7 2 5]
 [4 7 5 0 1 3 2 6 8 4]
 [8 5 7 3 4 2 1 6 0 8]
 [3 5 7 1 8 0 6 4 2 3]
 [0 6 4 8 7 3 1 5 2 0]
 [3 7 5 1 0 8 6 2 4 3]
 [3 6 1 4 2 5 0 7 8 3]
 [7 8 6 0 3 2 5 4 1 7]
 [4 8 6 1 3 2 5 7 0 4]]
GENOME_LENGTH 9
number_city [9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9]


In [ ]:
test_tsp.distanceNorm()

population [[2 4 7 6 8 5 1 0 3 2]
 [0 5 3 4 6 7 1 2 8 0]
 [2 0 7 6 4 8 3 1 5 2]
 [7 4 1 6 5 0 8 3 2 7]
 [6 0 3 2 5 7 8 4 1 6]
 [1 3 2 8 0 5 4 7 6 1]
 [6 8 7 3 4 2 0 1 5 6]
 [4 3 1 2 8 5 6 7 0 4]
 [0 2 6 7 5 4 3 1 8 0]
 [3 4 5 6 1 8 7 2 0 3]
 [6 1 4 3 5 2 0 8 7 6]
 [4 7 0 8 6 3 1 2 5 4]
 [3 7 1 2 0 4 8 5 6 3]
 [6 2 3 5 1 0 4 7 8 6]
 [7 3 2 0 4 1 6 5 8 7]
 [6 5 1 2 7 8 4 0 3 6]
 [3 6 1 8 2 7 4 5 0 3]
 [7 0 4 2 1 6 3 5 8 7]
 [8 2 4 1 0 7 3 6 5 8]
 [6 4 5 7 0 1 3 8 2 6]]
distances [1060.90583867 1102.2754154  1160.13865331 1320.07993978 1139.34055291
 1234.9500669  1235.86320193 1370.66463226 1342.06660032 1270.81262313
 1158.65409247 1280.85593456 1445.76323593 1025.36240818 1434.0233244
 1082.35297793 1138.96649017 1236.29663468 1341.13344243 1310.50264886]
arg distance [12 14  7  8 18  3 19 11  9 17  6  5  2 10  4 16  1 15  0 13]


TypeError: TSP.distanceNorm() missing 1 required positional argument: 'mask_cities'

In [ ]:
test_tsp.getKBest()

parent1 [8 5 3 1 0 6 7 2 4 8]
parent2 [6 1 8 5 3 2 7 4 0 6]
fitness_values [1.50271127 1.68520068 1.79298613 1.74634442 1.77787484 1.66278461
 1.6829178  1.5940118  1.67659258 1.74634442 1.65363561 1.77779312
 1.55206364 1.79298613 1.58127341 1.65363561 1.66147245 1.82640675
 1.81620287 1.72578825 1.85274135 1.72847169 1.82541805 1.78430029
 1.87160491]
argsort fitness_values [ 0 12 14  7 10 15 16  5  8  6  1 19 21  9  3 11  4 23  2 13 18 22 17 20
 24]
k_best [18 22 17 20 24]


In [ ]:
test_tsp.getKExtreme()

fitness_values [0.27095158 0.48318808 0.16995079 0.56128001 0.72580376 0.97282165
 0.15208856 0.62946978 0.81907158 0.49415273 0.69258259 0.72871755
 0.94508031 0.25932089 0.58641014 0.93985172 0.92613458 0.75923148
 0.48808997 0.96433633]
sort fitness_values [0.15208856 0.16995079 0.25932089 0.27095158 0.48318808 0.48808997
 0.49415273 0.56128001 0.58641014 0.62946978 0.69258259 0.72580376
 0.72871755 0.75923148 0.81907158 0.92613458 0.93985172 0.94508031
 0.96433633 0.97282165]
arg sort fitness_values [ 6  2 13  0  1 18  9  3 14  7 10  4 11 17  8 16 15 12 19  5]
arg_extreme [18  9  3 14  7 10  4 11 17  8 16 15 12 19  5]
extreme fitness [0.48808997 0.49415273 0.56128001 0.58641014 0.62946978 0.69258259
 0.72580376 0.72871755 0.75923148 0.81907158 0.92613458 0.93985172
 0.94508031 0.96433633 0.97282165]


In [ ]:
test_tsp.getKWeaks()

fitness_values [0.08972636 0.805041   0.25282856 0.19288404 0.29664141 0.53217379
 0.68928284 0.83240104 0.61711253 0.98334894 0.1448928  0.86925045
 0.98373475 0.35182599 0.67418031 0.64666247 0.84799916 0.44264535
 0.17803758 0.07054364]
sort fitness_values [0.98373475 0.98334894 0.86925045 0.84799916 0.83240104 0.805041
 0.68928284 0.67418031 0.64666247 0.61711253 0.53217379 0.44264535
 0.35182599 0.29664141 0.25282856 0.19288404 0.17803758 0.1448928
 0.08972636 0.07054364]
arg sort fitness_values [12  9 11 16  7  1  6 14 15  8  5 17 13  4  2  3 18 10  0 19]
arg_extreme [19  0 10 18  3  2  4 13 17  5]
extreme fitness [0.07054364 0.08972636 0.1448928  0.17803758 0.19288404 0.25282856
 0.29664141 0.35182599 0.44264535 0.53217379]


In [ ]:
test_tsp.permuteSimilarIndivids()

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
[[4 8 3 7 9 5 6 0 1 2]
 [4 2 3 9 8 6 5 7 1 0]
 [6 3 2 5 9 8 7 4 1 0]
 [3 1 5 7 4 9 6 8 0 2]]
population shape (10, 10)
False [6 3 2 5 9 8 7 4 1 0]
False [4 8 3 7 9 5 6 0 1 2]
False [4 2 3 9 8 6 5 7 1 0]
False [3 1 5 7 4 9 6 8 0 2]
True [3 1 5 7 4 9 6 8 0 2]
True [3 1 5 7 4 9 6 8 0 2]
True [6 3 2 5 9 8 7 4 1 0]
True [3 1 5 7 4 9 6 8 0 2]
True [6 3 2 5 9 8 7 4 1 0]
True [4 2 3 9 8 6 5 7 1 0]
similar size 6, population size 10
actual flag:   prev flag:    individ
False False [6 3 2 5 9 8 7 4 1 0]
False False [4 8 3 7 9 5 6 0 1 2]
False False [4 2 3 9 8 6 5 7 1 0]
False False [3 1 5 7 4 9 6 8 0 2]
False True [3 1 8 4 9 0 7 6 5 2]
False True [3 1 0 6 5 9 7 8 4 2]
False True [6 9 3 1 2 5 4 8 7 0]
False True [3 1 5 4 7 9 6 0 8 2]
False True [6 7 9 1 5 8 4 2 3 0]
False True [4 6 8 5 9 3 7 2 1 0]
