Description ????????????????????????

In [10]:
import numpy as np
import cv2 as cv
import yaml
from pathlib import Path
import sys
import pandas as pd

In [11]:
LCL_PATH = str(Path().cwd())
LCL_PATH

'c:\\Users\\Matei\\MLProjects\\UAIC-MIAO1\\Sem-1\\Metode-inspirate-din-natura\\Homeworks\\MIN\\laborator_1\\TTP'

In [12]:

# adding local_folder to the system path
sys.path.append(LCL_PATH)
sys.path.append("C:\\Users\\Matei\\MLProjects\\UAIC-MIAO1\\Sem-1\\Metode-inspirate-din-natura\\Homeworks\\MIN\\imshow.py")

def remove_modules(modules_name, *arg):
    if (modules_name in sys.modules):
        del sys.modules[modules_name]
        for key in arg:
            tmp_modules = "{}.{}".format(modules_name, key)
            del sys.modules[tmp_modules]

In [13]:

remove_modules("imshow")
remove_modules("builds.ttp_generator")
remove_modules("builds.genetic_optimizer_TSP")
remove_modules("builds.test_genetic_optimizer_TSP")

from builds.ttp_generator import *
from builds.genetic_optimizer_TSP import *
from builds.test_genetic_optimizer_TSP import *

# Test methods GA

### init

In [14]:
map_generator = TTPGenerator(nbr_city=9, max_distance=300)
map_of_distance = map_generator()
map_of_distance

array([[  0.        , 106.07544485,  76.21679605,  71.28113355,
        150.86417733, 283.28254447, 211.92923347, 146.1027036 ,
        292.26357967],
       [106.07544485,   0.        ,  68.68041933,  91.24143795,
        234.27334462, 281.57592227, 292.71487834,  99.12618221,
        338.24547299],
       [ 76.21679605,  68.68041933,   0.        ,  23.32380758,
        169.5788902 , 228.14030771, 226.21449998,  70.03570518,
        270.89665926],
       [ 71.28113355,  91.24143795,  23.32380758,   0.        ,
        146.41379716, 217.80725424, 202.89159667,  79.60527621,
        250.88842141],
       [150.86417733, 234.27334462, 169.5788902 , 146.41379716,
          0.        , 225.59476944,  61.07372594, 206.28620894,
        166.33099531],
       [283.28254447, 281.57592227, 228.14030771, 217.80725424,
        225.59476944,   0.        , 229.13096692, 185.0648535 ,
        141.226768  ],
       [211.92923347, 292.71487834, 226.21449998, 202.89159667,
         61.07372594, 229.1309

In [15]:
tsp = TSP()
tsp.setParameters(
    POPULATION_SIZE = 20,  # numarul populatiei
    MUTATION_RATE   = 0.01,   # threshold-ul pentru a face o mutatie genetica
    CROSSOVER_RATE  = 0.5,   # threshold-ul pentru incrucisarea parintilor
    SELECT_RATE     = 0.7,   # threshold-ul de selectie, selectare dupa compatibilitate sau dupa probabilitate
    K_DISTANCE      = 1.0,   # coeficientul de inhibare a distantei
    K_NBR_CITY      = 0.9,   # coeficientul de inhibare a numarului de orase
    GENERATIONS     = 100,   # numarul de generatii
    K_BEST          = 15,     # salveaza pentru urmatoarea generatie numarul de indivizi, cu cel mai mare scor
    K_WRONG         = 5,     # salveaza pentru urmatoarea generatie numarul de indivizi, cu cel mai mic scor
    )
tsp.setMap(map_of_distance)
test_tsp = TestTSP(tsp)

### test

In [16]:
test_tsp.initPopulation()

+++start
result [[3 7 6 5 8 0 1 2 4 3]
 [8 7 5 4 6 3 0 1 2 8]
 [6 8 5 0 3 4 7 1 2 6]
 [4 3 8 5 6 0 2 7 1 4]
 [8 3 1 2 7 4 0 5 6 8]
 [2 6 3 0 4 5 8 1 7 2]
 [8 1 3 2 6 0 4 7 5 8]
 [3 1 7 8 5 4 6 2 0 3]
 [4 3 8 0 6 1 5 7 2 4]
 [4 0 6 3 2 1 7 5 8 4]
 [1 6 4 8 2 0 5 7 3 1]
 [8 4 2 0 6 7 1 3 5 8]
 [7 1 2 8 6 0 4 5 3 7]
 [6 1 3 5 0 7 2 4 8 6]
 [3 7 6 8 1 0 5 2 4 3]
 [4 7 8 1 5 6 2 3 0 4]
 [2 1 5 7 6 0 8 4 3 2]
 [4 3 7 8 6 2 1 5 0 4]
 [7 8 5 2 0 3 6 1 4 7]
 [5 1 2 0 7 6 4 8 3 5]]


In [17]:
test_tsp.selectValidPopulation()

arg_parents1 [12  9  6 14 16]
fitness_values_parents1 [0.44378239 0.35788089 0.74235928 0.49870832 0.19527443]
result [ 0  1  2  3  4  5  6  7  8 10 11 13 15 17 18 19]


In [18]:
test_tsp.selectParent1()

fitness_values [0.43715657 0.90174687 0.05979825 0.00733247 0.56532748 0.07087406
 0.38751968 0.84886632 0.53462693 0.75634001 0.53207713 0.4906652
 0.05671804 0.05472387 0.36631684 0.23656803 0.32628046 0.14650391
 0.80350889 0.3146153 ]
fitness_values [ 3 13 12  2  5 17 15 19 16 14  6  0 11 10  8  4  9 18  7  1]
result [0.43715657 0.90174687 0.05979825 0.00733247 0.56532748 0.07087406
 0.38751968 0.84886632 0.53462693 0.75634001 0.53207713 0.4906652
 0.05671804 0.05472387 0.36631684 0.23656803 0.32628046 0.14650391
 0.80350889 0.3146153 ]


In [19]:
test_tsp.selectParent2()

fitness_values [0.97534577 0.11876331 0.56417231 0.7958139  0.44037057 0.0504064
 0.29674703 0.28650741 0.12886746 0.92876116 0.39233963 0.34701849
 0.83265677 0.40104022 0.24341128 0.48884506 0.89671477 0.24964331
 0.16430313 0.49309743]
argsort fitness_values [ 5  1  8 18 14 17  7  6 11 10 13  4 15 19  2  3 12 16  9  0]
fitness_partener 0.6805930944201716
result [17  8 13  9  0]
result [14  3 15 15 18]
result [ 0 11  7 15 15]
result [ 3 16 10 17 16]
result [16 16 15  6  0]
result [15 12 11 19 15]
result [15  0 15 12  0]
result [16 13 16 16 16]
result [19 18 16 11  4]
result [15 13 14 17 19]
result [16 16  3 19 19]
result [13 14 11 10  0]
result [ 5  9  8  5 16]
result [19  1 19 18 15]
result [18 12  1 16 15]
result [19  0  2 10  9]
result [ 1  2 10  0 12]
result [14  7  9 14 16]
result [ 3 19  9 16 17]
result [19 12  4 15 18]


In [20]:
test_tsp.crossover()

parent1 [8 0 3 1 5 2 6 4 7 8]
parent2 [8 7 4 2 6 5 3 0 1 8]
childs [[8 0 3 2 5 5 3 0 7 8]
 [8 7 4 2 6 2 6 4 7 8]
 [8 7 4 2 6 2 6 4 7 8]
 [8 0 3 1 6 2 3 0 1 8]
 [8 7 4 2 6 2 6 4 1 8]]
childs [[8 7 4 2 6 2 6 4 7 8]
 [8 0 3 1 5 5 3 0 1 8]
 [8 0 3 1 5 5 3 0 1 8]
 [8 7 4 1 6 2 3 4 7 8]
 [8 7 3 1 5 2 6 4 7 8]]
childs [[8 7 3 1 5 2 6 4 7 8]
 [8 0 3 1 5 2 6 4 7 8]
 [8 0 4 1 6 2 6 0 1 8]
 [8 7 3 1 5 5 6 0 7 8]
 [8 7 4 1 5 2 6 4 7 8]]
childs [[8 0 3 1 5 2 6 0 1 8]
 [8 7 4 2 6 5 3 0 1 8]
 [8 7 4 1 5 2 3 4 7 8]
 [8 0 3 1 5 5 3 0 1 8]
 [8 7 3 1 5 5 3 0 1 8]]
childs [[8 7 4 2 6 2 6 4 7 8]
 [8 0 3 1 5 2 3 0 1 8]
 [8 7 4 1 6 5 6 0 7 8]
 [8 7 4 1 5 2 6 4 1 8]
 [8 7 4 2 6 2 6 4 7 8]]
childs [[8 7 4 2 6 5 3 0 1 8]
 [8 0 3 1 5 5 3 0 1 8]
 [8 0 3 1 5 5 3 0 1 8]
 [8 7 4 2 5 2 6 4 7 8]
 [8 7 3 1 5 2 6 4 7 8]]
childs [[8 0 3 1 5 5 3 0 1 8]
 [8 0 3 2 6 2 6 4 7 8]
 [8 0 3 2 6 5 3 0 1 8]
 [8 7 3 1 6 5 3 4 7 8]
 [8 7 3 1 5 2 6 4 7 8]]
childs [[8 0 4 2 6 5 3 0 1 8]
 [8 7 4 2 6 2 6 4 7 8]
 [8 7 4 2 6 5 3 0 1 8]
 [8

In [21]:
test_tsp.mutate()

parent1 [3 1 8 4 7 0 5 2 6 3]
parent2 [5 4 6 3 8 0 1 2 7 5]
Operatia de mutatie a fost aplicata: [[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False  True False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]]
Operatia de mutatie a fost aplicata: [[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False  True False False False False False False False]]
Operatia de mutatie a fost aplicata: [[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False  True  True False False]
 [False 

In [22]:
test_tsp.getIndividDistance()

individ [2 6 0 1 4 5 7 8 3 2]
distance 1726.4233036136277


In [23]:
test_tsp.getIndividNumberCities()

individ [0 8 3 6 4 5 7 1 2 0]
number_city 9


In [24]:
test_tsp.getDistances()

population [[4 2 7 5 3 0 1 8 6 4]
 [1 8 3 5 0 2 4 6 7 1]
 [2 4 1 7 6 3 5 8 0 2]
 [3 2 6 0 8 7 4 5 1 3]
 [6 4 7 5 2 0 3 1 8 6]
 [4 7 2 1 3 0 6 5 8 4]
 [0 2 5 3 7 6 4 8 1 0]
 [3 2 6 0 1 4 5 7 8 3]
 [4 3 2 6 1 0 8 5 7 4]
 [5 7 1 8 0 2 4 6 3 5]
 [8 1 5 7 4 3 0 2 6 8]
 [3 5 6 4 7 2 8 1 0 3]
 [0 5 2 3 6 1 8 7 4 0]
 [1 6 0 7 3 4 5 8 2 1]
 [8 6 0 3 4 7 1 2 5 8]
 [2 8 0 5 4 1 6 3 7 2]
 [2 7 4 6 0 3 8 1 5 2]
 [2 8 6 5 0 4 1 3 7 2]
 [1 5 2 8 3 7 0 4 6 1]
 [1 0 7 2 4 8 5 3 6 1]]
distances [1351.54072639 1750.06175835 1687.2268825  1821.48838806 1389.92818258
 1256.14286866 1527.33774413 1726.42330361 1619.58383802 1642.26835147
 1663.67693039 1570.83257187 1988.80792278 1583.16450482 1305.46229633
 1951.55835386 1719.45613146 1541.70835788 1761.86207206 1512.76423639]


In [25]:
test_tsp.getNumberCities()

population [[2 6 7 3 0 4 8 1 5 2]
 [0 5 1 7 6 3 4 2 8 0]
 [7 4 0 1 2 5 6 3 8 7]
 [7 4 0 2 1 8 6 3 5 7]
 [4 7 2 5 1 8 6 3 0 4]
 [5 3 7 4 8 0 6 2 1 5]
 [1 2 0 3 7 5 4 8 6 1]
 [3 8 1 4 7 0 5 2 6 3]
 [2 3 1 4 6 5 0 7 8 2]
 [2 5 0 7 3 4 6 8 1 2]
 [1 4 3 0 8 2 5 7 6 1]
 [3 5 7 1 0 2 4 6 8 3]
 [3 6 4 5 0 1 2 8 7 3]
 [5 0 4 1 2 7 6 3 8 5]
 [4 7 3 1 6 8 5 2 0 4]
 [0 2 5 4 7 6 8 3 1 0]
 [2 0 4 3 6 1 5 7 8 2]
 [8 6 4 1 2 3 5 7 0 8]
 [7 0 1 5 4 6 2 8 3 7]
 [2 1 0 5 4 8 3 7 6 2]]
GENOME_LENGTH 9
number_city [9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9]


In [26]:
test_tsp.distanceNorm()

population [[5 3 0 8 4 1 7 2 6 5]
 [2 5 0 7 3 6 4 1 8 2]
 [6 4 1 0 3 2 8 5 7 6]
 [2 3 0 7 1 8 4 5 6 2]
 [0 7 5 3 4 2 8 6 1 0]
 [8 3 1 4 0 7 5 6 2 8]
 [2 3 7 5 1 6 8 4 0 2]
 [6 3 1 0 7 5 8 4 2 6]
 [0 2 3 4 5 7 1 6 8 0]
 [7 0 6 4 8 2 5 3 1 7]
 [4 6 7 5 1 2 8 3 0 4]
 [7 0 5 8 2 3 1 4 6 7]
 [4 6 3 1 2 5 8 0 7 4]
 [4 8 7 3 5 1 2 6 0 4]
 [2 0 6 5 3 8 4 7 1 2]
 [7 5 4 6 0 1 8 3 2 7]
 [3 7 6 4 0 1 8 5 2 3]
 [8 1 5 0 2 3 4 7 6 8]
 [4 0 6 7 1 3 5 2 8 4]
 [2 7 1 4 5 8 0 3 6 2]]
distances [1606.46366167 1844.51163147 1347.05820813 1525.35053158 1667.0327271
 1784.67706457 1388.07495252 1434.72719006 1473.0969099  1492.6484997
 1594.16778342 1505.26346226 1437.90674782 1666.06670689 1526.39647789
 1472.23143437 1382.39745143 1741.56526624 1690.17871832 1562.90757932]
arg distance [ 1  5 17 18  4 13  0 10 19 14  3 11  9  8 15 12  7  6 16  2]


TypeError: TSP.distanceNorm() missing 1 required positional argument: 'mask_cities'

In [ ]:
test_tsp.getKBest()

parent1 [8 5 3 1 0 6 7 2 4 8]
parent2 [6 1 8 5 3 2 7 4 0 6]
fitness_values [1.50271127 1.68520068 1.79298613 1.74634442 1.77787484 1.66278461
 1.6829178  1.5940118  1.67659258 1.74634442 1.65363561 1.77779312
 1.55206364 1.79298613 1.58127341 1.65363561 1.66147245 1.82640675
 1.81620287 1.72578825 1.85274135 1.72847169 1.82541805 1.78430029
 1.87160491]
argsort fitness_values [ 0 12 14  7 10 15 16  5  8  6  1 19 21  9  3 11  4 23  2 13 18 22 17 20
 24]
k_best [18 22 17 20 24]


In [ ]:
test_tsp.getKExtreme()

fitness_values [0.27095158 0.48318808 0.16995079 0.56128001 0.72580376 0.97282165
 0.15208856 0.62946978 0.81907158 0.49415273 0.69258259 0.72871755
 0.94508031 0.25932089 0.58641014 0.93985172 0.92613458 0.75923148
 0.48808997 0.96433633]
sort fitness_values [0.15208856 0.16995079 0.25932089 0.27095158 0.48318808 0.48808997
 0.49415273 0.56128001 0.58641014 0.62946978 0.69258259 0.72580376
 0.72871755 0.75923148 0.81907158 0.92613458 0.93985172 0.94508031
 0.96433633 0.97282165]
arg sort fitness_values [ 6  2 13  0  1 18  9  3 14  7 10  4 11 17  8 16 15 12 19  5]
arg_extreme [18  9  3 14  7 10  4 11 17  8 16 15 12 19  5]
extreme fitness [0.48808997 0.49415273 0.56128001 0.58641014 0.62946978 0.69258259
 0.72580376 0.72871755 0.75923148 0.81907158 0.92613458 0.93985172
 0.94508031 0.96433633 0.97282165]


In [ ]:
test_tsp.getKWeaks()

fitness_values [0.08972636 0.805041   0.25282856 0.19288404 0.29664141 0.53217379
 0.68928284 0.83240104 0.61711253 0.98334894 0.1448928  0.86925045
 0.98373475 0.35182599 0.67418031 0.64666247 0.84799916 0.44264535
 0.17803758 0.07054364]
sort fitness_values [0.98373475 0.98334894 0.86925045 0.84799916 0.83240104 0.805041
 0.68928284 0.67418031 0.64666247 0.61711253 0.53217379 0.44264535
 0.35182599 0.29664141 0.25282856 0.19288404 0.17803758 0.1448928
 0.08972636 0.07054364]
arg sort fitness_values [12  9 11 16  7  1  6 14 15  8  5 17 13  4  2  3 18 10  0 19]
arg_extreme [19  0 10 18  3  2  4 13 17  5]
extreme fitness [0.07054364 0.08972636 0.1448928  0.17803758 0.19288404 0.25282856
 0.29664141 0.35182599 0.44264535 0.53217379]


In [ ]:
test_tsp.permuteSimilarIndivids()

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
[[4 8 3 7 9 5 6 0 1 2]
 [4 2 3 9 8 6 5 7 1 0]
 [6 3 2 5 9 8 7 4 1 0]
 [3 1 5 7 4 9 6 8 0 2]]
population shape (10, 10)
False [6 3 2 5 9 8 7 4 1 0]
False [4 8 3 7 9 5 6 0 1 2]
False [4 2 3 9 8 6 5 7 1 0]
False [3 1 5 7 4 9 6 8 0 2]
True [3 1 5 7 4 9 6 8 0 2]
True [3 1 5 7 4 9 6 8 0 2]
True [6 3 2 5 9 8 7 4 1 0]
True [3 1 5 7 4 9 6 8 0 2]
True [6 3 2 5 9 8 7 4 1 0]
True [4 2 3 9 8 6 5 7 1 0]
similar size 6, population size 10
actual flag:   prev flag:    individ
False False [6 3 2 5 9 8 7 4 1 0]
False False [4 8 3 7 9 5 6 0 1 2]
False False [4 2 3 9 8 6 5 7 1 0]
False False [3 1 5 7 4 9 6 8 0 2]
False True [3 1 8 4 9 0 7 6 5 2]
False True [3 1 0 6 5 9 7 8 4 2]
False True [6 9 3 1 2 5 4 8 7 0]
False True [3 1 5 4 7 9 6 0 8 2]
False True [6 7 9 1 5 8 4 2 3 0]
False True [4 6 8 5 9 3 7 2 1 0]
