Test manager of root functionality

In [91]:
import sys
from pathlib import Path

from laborator_1.GeneticAlgoritmMethods.my_test.mutate import TestMutate

In [92]:
LCL_PATH = str(Path().cwd().parent)
LCL_PATH

'C:\\Users\\Matei\\MLProjects\\UAIC-MIAO1\\Sem-1\\Metode-inspirate-din-natura\\Homeworks\\MIN\\laborator_1\\GeneticAlgoritmMethods'

In [93]:

# adding local_folder to the system path
sys.path.append(LCL_PATH)

def remove_modules(modules_name, *arg):
    if (modules_name in sys.modules):
        del sys.modules[modules_name]
        for key in arg:
            tmp_modules = "{}.{}".format(modules_name, key)
            del sys.modules[tmp_modules]

In [94]:
remove_modules("my_code.algoritm_genetic")
remove_modules("my_test.algoritm_genetic")
remove_modules("my_code.callback")
remove_modules("my_test.callback")
remove_modules("my_code.crossover")
remove_modules("my_test.crossover")
remove_modules("my_code.fitness")
remove_modules("my_test.fitness")
remove_modules("my_code.individ_repair")
remove_modules("my_test.individ_repair")
remove_modules("my_code.init_population")
remove_modules("my_test.init_population")
remove_modules("my_code.metrics")
remove_modules("my_test.metrics")
remove_modules("my_code.mutate")
remove_modules("my_test.mutate")
remove_modules("my_code.root_GA")
remove_modules("my_test.root_GA")
remove_modules("my_code.select_parent")
remove_modules("my_test.select_parent")

from my_code.algoritm_genetic import *
from my_test.algoritm_genetic import *
from my_code.callback import *
from my_test.callback import *
from my_code.crossover import *
from my_test.crossover import *
from my_code.fitness import *
from my_test.fitness import *
from my_code.individ_repair import *
from my_test.individ_repair import *
from my_code.init_population import *
from my_test.init_population import *
from my_code.metrics import *
from my_test.metrics import *
from my_code.mutate import *
from my_test.mutate import *
from my_code.root_GA import *
from my_test.root_GA import *
from my_code.select_parent import *
from my_test.select_parent import *

In [95]:
GeneticAlgorithm().help()

'nume': numele obiectului
'extern_commnad_file': numele fisierului in care vor fi adaugate comenzile externe, (oprire fortata = stop=True)
'metric': Metrics: 
        metode de config: 'TSP'
'init_population': InitPopulation:
        metode de config: 'vecin', 'TSP_aleator'
'fitness': Fitness: 
        metode de config: 'TSP_f1score', 'TTP_linear', 'TTP_exp', 'TSP_norm', 
'select_parent': {'select_parent1': 'select_parent2'}: SelectParent: 
        metode de config: 'choice', 'roata', 'turneu', 'turneu_choice', 'crescator', 'mixt'
'crossover': Crossover: 
        metode de config: 'diff', 'split', 'perm_sim', 'mixt', 
'mutate': Mutate: 
        metode de config: 'inversion', 'scramble', 'swap', 'roll', 'insertion', 'rool_sim', 'perm_sim', 'flip_sim', 'mixt', 
'callback': Callback: 
        metode de config: 'filename'



# Test methods Mutate

In [96]:
obj_mutate = Mutate("")
obj_mutate(None, None, None)

In [97]:
obj_mutate = Mutate("swap")
obj_mutate(None, None, None)

In [98]:
test_mutate = TestMutate("inversion")
test_mutate.test("inversion")
print(test_mutate.GENOME_LENGTH)
print(test_mutate.MUTATION_RATE)

AttributeError: 'TestMutate' object has no attribute 'test'

In [47]:

print(test_mutate.MUTATION_RATE)
print(obj_mutate.MUTATION_RATE)
test_mutate.MUTATION_RATE=0.01
print(test_mutate.MUTATION_RATE)
print(obj_mutate.MUTATION_RATE)

0.9
0.01
0.01
0.01


# Test crossover

In [48]:
obj_crossover = Crossover(mutate="")
obj_crossover(None, None)

TypeError: Crossover.__init__() got an unexpected keyword argument 'mutate'

In [ ]:
obj_crossover = Crossover(crossover="")
obj_crossover(None, None)

In [ ]:
from laborator_1.GeneticAlgoritmMethods.my_test.crossover import TestCrossover

obj_crossover = TestCrossover("diff")
obj_crossover.test("diff")

In [ ]:

print(obj_crossover.MUTATION_RATE)

# Test other

### init

In [15]:
map_generator = TTPGenerator(nbr_city=9, max_distance=300)
map_of_distance = map_generator()
map_of_distance

NameError: name 'TTPGenerator' is not defined

In [ ]:
tsp = TSP()
tsp.setParameters(
    POPULATION_SIZE = 20,  # numarul populatiei
    MUTATION_RATE   = 0.01,   # threshold-ul pentru a face o mutatie genetica
    CROSSOVER_RATE  = 0.5,   # threshold-ul pentru incrucisarea parintilor
    SELECT_RATE     = 0.7,   # threshold-ul de selectie, selectare dupa compatibilitate sau dupa probabilitate
    K_DISTANCE      = 1.0,   # coeficientul de inhibare a distantei
    K_NBR_CITY      = 0.9,   # coeficientul de inhibare a numarului de orase
    GENERATIONS     = 100,   # numarul de generatii
    K_BEST          = 15,     # salveaza pentru urmatoarea generatie numarul de indivizi, cu cel mai mare scor
    K_WRONG         = 5,     # salveaza pentru urmatoarea generatie numarul de indivizi, cu cel mai mic scor
    )
tsp.setMap(map_of_distance)
test_tsp = TestTSP(tsp)

### Algotrithm Genetic Test

In [62]:
print("\n=== Test GeneticAlgorithm ===")
t = TestGeneticAlgorithm()

t.test_run()
t.test_help()
t.test_setParameters()
t.test_evolutionMonitor()
t.test_showMetrics()
t.test_stres()
t.test_getArgsWeaks()
t.test_getArgsElite()
t.test_setElites()
t.test_setElitesByFitness()
t.test_setDataset()


=== Test GeneticAlgorithm ===
Utilizezi metoda: TSP, datele de antrenare trebuie sa corespunda metodei de calcul a metricilor!!!

=== test_run (__call__) ===
population (5, 5)
Name:unitGA, Generatia: 0, score: 14.0, best_fitness: 1.0, 
best: [0 1 4 2 3]

=== test_help ===
'nume': numele obiectului
'extern_commnad_file': numele fisierului in care vor fi adaugate comenzile externe, (oprire fortata = stop=True)
'metric': Metrics: 
        metode de config: 'TSP'
'init_population': InitPopulation:
        metode de config: 'vecin', 'TSP_aleator'
'fitness': Fitness: 
        metode de config: 'TSP_f1score', 'TTP_linear', 'TTP_exp', 'TSP_norm', 
'select_parent': {'select_parent1': 'select_parent2'}: SelectParent: 
        metode de config: 'choice', 'roata', 'turneu', 'turneu_choice', 'crescator', 'mixt'
'crossover': Crossover: 
        metode de config: 'diff', 'split', 'perm_sim', 'mixt', 
'mutate': Mutate: 
        metode de config: 'inversion', 'scramble', 'swap', 'roll', 'insertion', '

### Callback test

In [10]:
print("\n=== Test Callback ===")
TestCallback("log_test.csv").test()


=== Test Callback ===
Test finished — check file: log_test.csv


### Crossover Test

In [99]:
t = TestCrossover()

t.test_diff()
t.test_split()
t.test_perm_sim()
t.test_flip_sim()
t.test_mixt()



=== diff ===
parent1: [9 6 8 1 8 9 4 9 7 5 9]
parent2: [9 9 6 1 8 9 4 9 1 7 5]
-1 (5,) (5,)
attempt 1:
before: [9 6 8 1 8 9 4 9 7 5 9]
after : [9 8 5 1 8 9 4 9 6 1 7]
diff idx: [ 1  2  8  9 10]

=== split ===
parent1: [9 6 8 1 8 9 4 9 7 5 9]
parent2: [9 9 6 1 8 9 4 9 1 7 5]
attempt 1:
before: [9 6 8 1 8 9 4 9 7 5 9]
after : [9 6 6 1 8 9 4 9 1 5 9]
diff idx: [2 8]

=== perm_sim ===
parent1: [9 6 8 1 8 9 4 9 7 5 9]
parent2: [9 9 6 1 8 9 4 9 1 7 5]
attempt 1:
before: [9 6 8 1 8 9 4 9 7 5 9]
after : [9 6 8 9 4 8 1 9 7 5 9]
diff idx: [3 4 5 6]

=== flip_sim ===
parent1: [9 6 8 1 8 9 4 9 7 5 9]
parent2: [9 9 6 1 8 9 4 9 1 7 5]
attempt 1:
before: [9 6 8 1 8 9 4 9 7 5 9]
after : [9 6 8 9 4 9 8 1 7 5 9]
diff idx: [3 4 6 7]

=== mixt ===
parent1: [9 6 8 1 8 9 4 9 7 5 9]
parent2: [9 9 6 1 8 9 4 9 1 7 5]
attempt 1:
before: [9 6 8 1 8 9 4 9 7 5 9]
after : [9 6 8 9 1 4 8 9 7 5 9]
diff idx: [3 4 5 6]


### Fitness Test

In [12]:
tf = TestFitness()

tf.test_TSP_f1()
tf.test_TTP_linear()
tf.test_TTP_exp()

Utilizezi metoda: TSP, datele de antrenare trebuie sa corespunda metodei de calcul a metricilor!!!
Utilizezi metoda: TTP, datele de antrenare trebuie sa corespunda metodei de calcul a metricilor!!!

=== TEST TSP F1score ===
[0. 0.]

=== TEST TTP Linear ===
[127.03778169 126.49129307]

=== TEST TTP Exp ===
[116.18652525 121.35206654]


### Individ repair test

In [ ]:
#TO DO

### Init Population Test

In [13]:
t = TestInitPopulation()
t.test_help()
t.test_abstract()
t.test_TSP_random()
t.test_init_TTP()


Utilizezi metoda: TTP, datele de antrenare trebuie sa corespunda metodei de calcul a metricilor!!!

=== test_help ===
InitPopulation:
        metode de config: 'vecin', 'TSP_aleator'


=== test_abstract ===
OK abstract throws: Lipseste configuratia pentru functia de 'InitPopulation': config 'unknown'

=== test_TSP_random ===
population (10, 5)
shape = (10, 5)
[[1 3 0 2 4]
 [1 0 3 2 4]
 [2 4 0 3 1]]

=== test_init_TTP ===
shape = (9, 6)
[[4 0 1 2 3 4]
 [0 4 2 3 1 0]
 [3 2 4 0 1 3]]

--- internal _constructGreedyRoute ---
[0 4 3 2 1 0]

--- internal _twoOpt ---
before: [0 4 3 2 1 0]
after : [0 4 3 2 1 0]


### Metrics Test

In [15]:
t = TestMetrics()
t.test_help()

# TSP tests
t.test_metricsTSP()
t.test_scoreTSP()

# TTP tests
t.test_metricsTTP()
t.test_speedTTP()
t.test_scoreTTP()

Utilizezi metoda: TSP, datele de antrenare trebuie sa corespunda metodei de calcul a metricilor!!!
Utilizezi metoda: TTP, datele de antrenare trebuie sa corespunda metodei de calcul a metricilor!!!

=== test_help ===
TSP -> Metrics: 
        metode de config: 'TSP'

TTP -> Metrics: 
        metode de config: 'TSP'


=== test_metricsTSP ===
{'distances': array([14., 12.]), 'number_city': array([4, 4])}

=== test_scoreTSP ===
{'score': np.float64(12.0), 'best_fitness': np.float64(0.9)}

=== test_metricsTTP ===
{'distances': array([14., 16.], dtype=float32), 'profits': array([150., 150.], dtype=float32), 'times': array([14.39056 , 16.815063], dtype=float32)}

=== test_speedTTP ===
W= 0 → v= 1.0
W= 3 → v= 0.865
W= 10 → v= 0.55

=== test_scoreTTP ===
{'score': np.float64(16.0), 'best_fitness': np.float64(0.8)}


### Mutate Test

In [16]:
t = TestMutate("")

t.test_swap()
t.test_scramble()
t.test_inversion()
t.test_roll()
t.test_insertion()
t.test_diff_swap()
t.test_roll_sim()
t.test_perm_sim()
t.test_flip_sim()
t.test_mixt()



=== swap ===
p1: [9 5 4 2 3 8 6 7 1 0 9]
p2: [9 1 4 0 5 2 8 6 3 7 9]
before: [9 3 2 1 6 7 5 4 8 0 9]
after : [9 8 2 1 6 7 5 4 3 0 9]
diff : [(1, 3, 8), (8, 8, 3)]

=== scramble ===
p1: [9 5 4 2 3 8 6 7 1 0 9]
p2: [9 1 4 0 5 2 8 6 3 7 9]
before: [9 3 2 1 6 7 5 4 8 0 9]
after : [9 3 2 1 6 7 5 4 8 0 9]
diff : []

=== inversion ===
p1: [9 5 4 2 3 8 6 7 1 0 9]
p2: [9 1 4 0 5 2 8 6 3 7 9]
before: [9 3 2 1 6 7 5 4 8 0 9]
after : [9 3 2 6 1 7 5 4 8 0 9]
diff : [(3, 1, 6), (4, 6, 1)]

=== roll ===
p1: [9 5 4 2 3 8 6 7 1 0 9]
p2: [9 1 4 0 5 2 8 6 3 7 9]
before: [9 3 2 1 6 7 5 4 8 0 9]
after : [4 8 0 9 9 3 2 1 6 7 5]
diff : [(0, 9, 4), (1, 3, 8), (2, 2, 0), (3, 1, 9), (4, 6, 9), (5, 7, 3), (6, 5, 2), (7, 4, 1), (8, 8, 6), (9, 0, 7), (10, 9, 5)]

=== insertion ===
p1: [9 5 4 2 3 8 6 7 1 0 9]
p2: [9 1 4 0 5 2 8 6 3 7 9]
before: [9 3 2 1 6 7 5 4 8 0 9]
after : [9 3 2 6 7 5 4 8 1 0 9]
diff : [(3, 1, 6), (4, 6, 7), (5, 7, 5), (6, 5, 4), (7, 4, 8), (8, 8, 1)]

=== diff_swap ===
p1: [9 5 4 2 3 8 6 7 1 

### Root GA Test

In [17]:
t = TestRootGA()
t.GENOME_LENGTH   = 8
t.POPULATION_SIZE = 5

pop = t.initPopulation()
print(pop)

[[7 4 3 6 2 1 0 5 7]
 [7 6 1 4 2 3 5 0 7]
 [7 4 2 6 3 1 5 0 7]
 [7 0 1 4 5 6 3 2 7]
 [7 1 0 6 4 5 3 2 7]]


### Select Parent Test

In [18]:
t = TestSelectParent()

t.test_choice()
t.test_roata()
t.test_turneu()
t.test_turneu_choice()
t.test_crescator()
t.test_mixt()


=== choice ===
DEBUG POPULATION_SIZE = 4
picks: [2, 1, 2, 0, 2, 3, 2, 2, 1, 2, 1, 1, 2, 0, 3, 0, 2, 1, 2, 3]

=== roata ===
DEBUG POPULATION_SIZE = 4
picks: [1, 2, 2, 2, 1, 3, 2, 3, 2, 1, 3, 2, 3, 2, 3, 2, 2, 2, 3, 2]

=== turneu ===
DEBUG POPULATION_SIZE = 4
picks: [2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 3, 2, 2, 2]

=== turneu_choice ===
DEBUG POPULATION_SIZE = 4
picks: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]

=== crescator ===
DEBUG POPULATION_SIZE = 4
picks: [0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]

=== mixt ===
DEBUG POPULATION_SIZE = 4
picks: [0, 2, 1, 1, 2, 2, 2, 3, 2, 2, 0, 1, 2, 1, 2, 1, 2, 2, 3, 2]
