Test manager of root functionality

In [1]:
import numpy as np
import sys
from pathlib import Path
import pathlib

In [2]:
LCL_PATH = str(Path().cwd().parent)
LCL_PATH

'c:\\Users\\Matei\\MLProjects\\UAIC-MIAO1\\Sem-1\\Metode-inspirate-din-natura\\Homeworks\\MIN\\laborator_1\\GeneticAlgoritmMethods'

In [3]:

# adding local_folder to the system path
sys.path.append(LCL_PATH)

def remove_modules(modules_name, *arg):
    if (modules_name in sys.modules):
        del sys.modules[modules_name]
        for key in arg:
            tmp_modules = "{}.{}".format(modules_name, key)
            del sys.modules[tmp_modules]

In [4]:
remove_modules("my_code.algoritm_genetic")
remove_modules("my_test.algoritm_genetic")
remove_modules("my_code.callback")
remove_modules("my_test.callback")
remove_modules("my_code.crossover")
remove_modules("my_test.crossover")
remove_modules("my_code.fitness")
remove_modules("my_test.fitness")
remove_modules("my_code.individ_repair")
remove_modules("my_test.individ_repair")
remove_modules("my_code.init_population")
remove_modules("my_test.init_population")
remove_modules("my_code.metrics")
remove_modules("my_test.metrics")
remove_modules("my_code.mutate")
remove_modules("my_test.mutate")
remove_modules("my_code.root_GA")
remove_modules("my_test.root_GA")
remove_modules("my_code.select_parent")
remove_modules("my_test.select_parent")

from my_code.algoritm_genetic import *
from my_test.algoritm_genetic import *
from my_code.callback import *
from my_test.callback import *
from my_code.crossover import *
from my_test.crossover import *
from my_code.fitness import *
from my_test.fitness import *
from my_code.individ_repair import *
from my_test.individ_repair import *
from my_code.init_population import *
from my_test.init_population import *
from my_code.metrics import *
from my_test.metrics import *
from my_code.mutate import *
from my_test.mutate import *
from my_code.root_GA import *
from my_test.root_GA import *
from my_code.select_parent import *
from my_test.select_parent import *

In [5]:
GeneticAlgorithm().help()

TypeError: Mutate.__init__() got an unexpected keyword argument 'mutate'

# Test methods Mutate

In [ ]:
obj_mutate = Mutate("")
obj_mutate(None, None, None)

In [ ]:
obj_mutate = Mutate("swap")
obj_mutate(None, None, None)

Mutate, testParentClass GENOME_LENGTH :8


In [ ]:
test_mutate = TestMutate("inversion")
test_mutate.test("inversion")
print(test_mutate.GENOME_LENGTH)
print(test_mutate.MUTATION_RATE)

parent1 [7 6 1 4 5 2 0 3 7]
parent2 [7 4 1 3 6 5 0 2 7]
offspring [7 6 4 1 3 2 0 5 7]
Operatia de mutatie a fost aplicata: [False False  True False False False  True False False]
Operatia de mutatie a fost aplicata: [False False False False False False  True  True False]
Operatia de mutatie 'lipseste'
Operatia de mutatie a fost aplicata: [False False False False False  True  True False False]
Operatia de mutatie a fost aplicata: [False False False False False False  True  True False]
Operatia de mutatie 'lipseste'
Operatia de mutatie a fost aplicata: [False False False  True False  True False False False]
Operatia de mutatie a fost aplicata: [False False False False False False  True  True False]
Operatia de mutatie a fost aplicata: [False False  True False False  True False False False]
Operatia de mutatie 'lipseste'
8
0.9


In [ ]:

print(test_mutate.MUTATION_RATE)
print(obj_mutate.MUTATION_RATE)
test_mutate.MUTATION_RATE=0.01
print(test_mutate.MUTATION_RATE)
print(obj_mutate.MUTATION_RATE)

# Test crossover

In [ ]:
obj_crossover = Crossover(mutate="")
obj_crossover(None, None)

In [ ]:
obj_crossover = Crossover(crossover="")
obj_crossover(None, None)

In [ ]:
obj_crossover = TestCrossover(crossover="diff")
obj_crossover.test("diff")

In [ ]:

print(obj_crossover.MUTATION_RATE)

0.9


# Test other

### init

In [ ]:
map_generator = TTPGenerator(nbr_city=9, max_distance=300)
map_of_distance = map_generator()
map_of_distance

In [ ]:
tsp = TSP()
tsp.setParameters(
    POPULATION_SIZE = 20,  # numarul populatiei
    MUTATION_RATE   = 0.01,   # threshold-ul pentru a face o mutatie genetica
    CROSSOVER_RATE  = 0.5,   # threshold-ul pentru incrucisarea parintilor
    SELECT_RATE     = 0.7,   # threshold-ul de selectie, selectare dupa compatibilitate sau dupa probabilitate
    K_DISTANCE      = 1.0,   # coeficientul de inhibare a distantei
    K_NBR_CITY      = 0.9,   # coeficientul de inhibare a numarului de orase
    GENERATIONS     = 100,   # numarul de generatii
    K_BEST          = 15,     # salveaza pentru urmatoarea generatie numarul de indivizi, cu cel mai mare scor
    K_WRONG         = 5,     # salveaza pentru urmatoarea generatie numarul de indivizi, cu cel mai mic scor
    )
tsp.setMap(map_of_distance)
test_tsp = TestTSP(tsp)

### test

In [ ]:
test_tsp.initPopulation()

In [ ]:
test_tsp.selectValidPopulation()

In [ ]:
test_tsp.selectParent1()

In [ ]:
test_tsp.selectParent2()

In [ ]:
test_tsp.crossover()

In [ ]:
test_tsp.mutate()

In [ ]:
test_tsp.getIndividDistance()

In [ ]:
test_tsp.getIndividNumberCities()

In [ ]:
test_tsp.getDistances()

In [ ]:
test_tsp.getNumberCities()

In [ ]:
test_tsp.distanceNorm()

In [ ]:
test_tsp.getKBest()

In [ ]:
test_tsp.getKExtreme()

In [ ]:
test_tsp.getKWeaks()

In [ ]:
test_tsp.permuteSimilarIndivids()

### Metrics Test

In [6]:
tm = TestMetrics()
tm.test()

Utilizezi metoda: tsp, datele de antrenare trebuie sa corespunda metodei de calcul a metricilor!!!

=== TEST METRICS ===
Distance matrix:
 [[0. 3. 5. 4. 3.]
 [3. 0. 4. 5. 3.]
 [5. 4. 0. 3. 3.]
 [4. 5. 3. 0. 3.]
 [3. 3. 3. 3. 0.]]
Population:
 [[0 1 2 3 0]
 [0 4 2 1 0]
 [3 2 4 1 3]]

Distances:    [14. 13. 14.]
Num. cities:  [4 4 4]

Pairwise distance test: 5.0

=== TTP speed test ===
Wcur =   0  → v = 1.0000
Wcur =  10  → v = 0.9550
Wcur =  50  → v = 0.7750
Wcur = 200  → v = 0.1000

=== TTP individ TTP-distance test ===
individ [0, 1, 2, 3, 0]  → TTP distance = 14.0
individ [0, 4, 2, 1, 0]  → TTP distance = 13.0
individ [3, 2, 4, 1, 3]  → TTP distance = 14.0
