Test manager of root functionality

In [1]:

import sys
from pathlib import Path
import seaborn as sns

In [2]:

LCL_PATH  = str(Path().cwd().parent.parent)
ROOT_PATH = str(Path(LCL_PATH).parent.parent)
EXTERN_CMD_PATH = str(Path(ROOT_PATH))
GENERIC_PATH    = str(Path(ROOT_PATH)/"GeneticAlgorithmManager")
SPECIFIC_PATH   = str(Path(ROOT_PATH)/"extension")
print("""
root path:\t{}
local path:\t{}
generic_path:\t{}
project_specific_path:\t{}
extern_cmd_path: \t{}""".format(ROOT_PATH, LCL_PATH, GENERIC_PATH, SPECIFIC_PATH, EXTERN_CMD_PATH))


root path:	/home/gheorghe/Desktop/Proiecte/master/MIN_metode_inspirate_din_natura
local path:	/home/gheorghe/Desktop/Proiecte/master/MIN_metode_inspirate_din_natura/laborator_1/TTP
generic_path:	/home/gheorghe/Desktop/Proiecte/master/MIN_metode_inspirate_din_natura/GeneticAlgorithmManager
project_specific_path:	/home/gheorghe/Desktop/Proiecte/master/MIN_metode_inspirate_din_natura/extension
extern_cmd_path: 	/home/gheorghe/Desktop/Proiecte/master/MIN_metode_inspirate_din_natura


In [3]:

# adding local_folder to the system path
sys.path.append(LCL_PATH)
sys.path.append(ROOT_PATH)
sys.path.append(GENERIC_PATH)
sys.path.append(SPECIFIC_PATH)

from sys_function import * # este in root

In [71]:

sys_remove_modules("imshow")
sys_remove_modules("extension.utils.normalization")
sys_remove_modules("builds.dataset_man.dataset_ttp_man")
sys_remove_modules("builds.metrics.metrics_ttp_base")

from imshow import *
from extension.utils.normalization import *
from builds.dataset_man.dataset_ttp_man import *
from builds.metrics.metrics_ttp_base import *

# Data aquisition

In [72]:

dataset_man_obj = DatasetTTPMan("{}/data".format(LCL_PATH))
dataset = dataset_man_obj(nodes_file="NODE_COORD_SECTION.csv",
                        items_file="ITEMS_SECTION.csv")

metrics_obj = MetricsTTPBase(dataset, 0)

In [73]:

filename_population = "{}/ant_routes.npy".format(LCL_PATH)
with open(filename_population, 'rb') as f:
    ant_routes = np.load(f)

# CrossoverPartition

## Similarity test

In [89]:

def similarity_gene(parent1, parent2):
    arr1, arr2 = np.nonzero(parent1 == parent2.reshape(-1, 1))
    #print("arr1 {},\narr2 {}".format(arr1, arr2))
    mask = np.abs(arr2[1:]-arr2[:-1])==1
    #print("mask", mask)
    #
    sim_map = []
    lenght = 0
    start_idx = 0
    for idx, bit in enumerate(mask):
        if (bit == False):
            sim_map.append([start_idx, start_idx+lenght+1])
            start_idx = idx+1
            lenght = 0
        else:
            lenght += 1
    else:
        sim_map.append([start_idx, start_idx+lenght+1])
    return sim_map

def show_similarity(sim_map):
    for start_idx, end_idx in sim_map:
        print(parent2[start_idx:end_idx])


In [61]:

parent1 = np.arange(20)
parent2 = parent1.copy()
sim_map = similarity_gene(parent1, parent2)
show_similarity(sim_map)

arr1 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19],
arr2 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
mask [ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [62]:

parent2 = parent1.copy()
parent2[7:13] = np.flip(parent2[7:13])
sim_map = similarity_gene(parent1, parent2)
show_similarity(sim_map)

arr1 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19],
arr2 [ 0  1  2  3  4  5  6 12 11 10  9  8  7 13 14 15 16 17 18 19]
mask [ True  True  True  True  True  True False  True  True  True  True  True
 False  True  True  True  True  True  True]
[0 1 2 3 4 5 6]
[12 11 10  9  8  7]
[13 14 15 16 17 18 19]


In [64]:

parent2 = parent1.copy()
parent2[7:13] = np.random.permutation(parent2[7:13])
sim_map = similarity_gene(parent1, parent2)
show_similarity(sim_map)

arr1 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19],
arr2 [ 0  1  2  3  4  5  6 10  9 11  8  7 12 13 14 15 16 17 18 19]
mask [ True  True  True  True  True  True False  True False False  True False
  True  True  True  True  True  True  True]
[0 1 2 3 4 5 6]
[10  9]
[11]
[8 7]
[12 13 14 15 16 17 18 19]


In [65]:

parent2 = parent1.copy()
parent2[7:13] = np.roll(parent2[7:13], 2)
sim_map = similarity_gene(parent1, parent2)
show_similarity(sim_map)

arr1 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19],
arr2 [ 0  1  2  3  4  5  6 11 12  7  8  9 10 13 14 15 16 17 18 19]
mask [ True  True  True  True  True  True False  True False  True  True  True
 False  True  True  True  True  True  True]
[0 1 2 3 4 5 6]
[11 12]
[ 7  8  9 10]
[13 14 15 16 17 18 19]


In [66]:

parent2 = parent1.copy()
parent2 = np.roll(parent2, 3)
parent2[7:13] = np.roll(parent2[7:13], 2)
sim_map = similarity_gene(parent1, parent2)
show_similarity(sim_map)

arr1 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19],
arr2 [17 18 19  0  1  2  3  8  9  4  5  6  7 10 11 12 13 14 15 16]
mask [ True  True False  True  True  True False  True False  True  True  True
 False  True  True  True  True  True  True]
[17 18 19]
[0 1 2 3]
[8 9]
[4 5 6 7]
[10 11 12 13 14 15 16]


In [67]:

parent2 = parent1.copy()
parent2[1:] = np.roll(parent2[1:], 3)
parent2[7:13] = np.flip(parent2[7:13])
sim_map = similarity_gene(parent1, parent2)
show_similarity(sim_map)

arr1 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19],
arr2 [ 0 17 18 19  1  2  3  9  8  7  6  5  4 10 11 12 13 14 15 16]
mask [False  True  True False  True  True False  True  True  True  True  True
 False  True  True  True  True  True  True]
[0]
[17 18 19]
[1 2 3]
[9 8 7 6 5 4]
[10 11 12 13 14 15 16]


In [68]:

parent2 = parent1.copy()
parent2[1:] = np.roll(parent2[1:], 3)
parent2[7:13] = np.flip(parent2[7:13])
parent2[13:] = np.random.permutation(parent2[13:])
print("parent2", parent2)
sim_map = similarity_gene(parent1, parent2)
show_similarity(sim_map)

parent2 [ 0 17 18 19  1  2  3  9  8  7  6  5  4 15 11 10 14 13 12 16]
arr1 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19],
arr2 [ 0 17 18 19  1  2  3  9  8  7  6  5  4 15 11 10 14 13 12 16]
mask [False  True  True False  True  True False  True  True  True  True  True
 False False  True False  True  True False]
[0]
[17 18 19]
[1 2 3]
[9 8 7 6 5 4]
[15]
[11 10]
[14 13 12]
[16]


## Route test

In [ ]:

for route in ant_routes[:5]:
    map_all = dataset_man_obj.putRouteOnMap(route)
    new_distance = metrics_obj.computeIndividDistance(route)
    print("distance: {}".format(new_distance))
    image_show_wait(map_all, window_name="All")

In [91]:

parent1, parent2 = ant_routes[:2]
#print(parent1)
#print(parent2)
sim_map = similarity_gene(parent1, parent2)
#show_similarity(sim_map)

tmp_distance1 = metrics_obj.computeIndividDistance(parent1)
tmp_distance2 = metrics_obj.computeIndividDistance(parent2)
print("tmp_distance1 {}, tmp_distance2 {}".format(tmp_distance1, tmp_distance2))
for start_idx, end_idx in sim_map:
    tmp_parent1 = parent1[start_idx:end_idx]
    tmp_parent2 = parent2[start_idx:end_idx]
    tmp_distance1 = metrics_obj.computeIndividDistance(tmp_parent1)
    tmp_distance2 = metrics_obj.computeIndividDistance(tmp_parent2)
    print("tmp_distance1 {}, tmp_distance2 {}, is_same {}".format(tmp_distance1, tmp_distance2, tmp_parent1[0]==tmp_parent2[0]))

tmp_distance1 2781.0, tmp_distance2 2785.0
tmp_distance1 1379.0, tmp_distance2 1379.0, is_same True
tmp_distance1 66.0, tmp_distance2 80.0, is_same False
tmp_distance1 16.0, tmp_distance2 16.0, is_same False
tmp_distance1 80.0, tmp_distance2 73.0, is_same False
tmp_distance1 1704.0, tmp_distance2 1704.0, is_same True


In [98]:

tmp_groups_route = []
for start_idx, end_idx in sim_map[1:4]:
    print("Start")
    tmp_parent1 = parent1[start_idx:end_idx]
    tmp_parent2 = parent2[start_idx:end_idx]
    tmp_distance1 = metrics_obj.computeIndividDistance(tmp_parent1)
    tmp_distance2 = metrics_obj.computeIndividDistance(tmp_parent2)
    if (tmp_distance1 <= tmp_distance2):
        print(tmp_parent1, "*")
        print(tmp_parent2)
    else:
        print(tmp_parent1)
        print(tmp_parent2, "*")

Start
[ 87 111 109 107 108  88  80] *
[113 116 114 115  85  84  83]
Start
[81 82] *
[111  87]
Start
[ 83  84  85 115 114 116 113]
[ 82  81  80  88 108 107 109] *
