Test manager of root functionality

In [1]:

import sys
from pathlib import Path
import seaborn as sns

In [2]:

LCL_PATH = str(Path().cwd().parent)
GLOBAL_PATH = str(Path().cwd().parent.parent.parent)
DATASET_PATH = str(Path(GLOBAL_PATH).joinpath("laborator_1", "TTP"))
info = """local path:\t{}
global path:\t{}
dataset path:\t{}""".format(LCL_PATH, GLOBAL_PATH, DATASET_PATH)
print(info)

local path:	/home/gheorghe/Desktop/Proiecte/master/MIN_metode_inspirate_din_natura/extension/init_population
global path:	/home/gheorghe/Desktop/Proiecte/master/MIN_metode_inspirate_din_natura
dataset path:	/home/gheorghe/Desktop/Proiecte/master/MIN_metode_inspirate_din_natura/laborator_1/TTP


In [3]:

# adding local_folder to the system path
sys.path.append(LCL_PATH)
sys.path.append(GLOBAL_PATH)
sys.path.append(DATASET_PATH)

def remove_modules(modules_name, *arg):
    if (modules_name in sys.modules):
        del sys.modules[modules_name]
        for key in arg:
            tmp_modules = "{}.{}".format(modules_name, key)
            del sys.modules[tmp_modules]

In [47]:

remove_modules("my_code.recursiv_init_population")

remove_modules("builds.ttp_generator")

from builds.ttp_generator import *

from my_code.recursiv_init_population import *

# Data aquisition

In [5]:

ttp_generator = TTPGenerator("{}/data".format(DATASET_PATH))
dataset = ttp_generator(nodes_file="NODE_COORD_SECTION.csv",
                        items_file="ITEMS_SECTION.csv")
dataset

{'GENOME_LENGTH': 280,
 'distance': array([[ 0., 20., 24., ..., 43., 34., 18.],
        [20.,  0., 18., ..., 36., 28.,  9.],
        [24., 18.,  0., ..., 20., 11., 10.],
        ...,
        [43., 36., 20., ...,  0.,  9., 29.],
        [34., 28., 11., ...,  9.,  0., 20.],
        [18.,  9., 10., ..., 29., 20.,  0.]], shape=(280, 280)),
 'coords': array([[288, 149],
        [288, 129],
        [270, 133],
        [256, 141],
        [256, 157],
        [246, 157],
        [236, 169],
        [228, 169],
        [228, 161],
        [220, 169],
        [212, 169],
        [204, 169],
        [196, 169],
        [188, 169],
        [196, 161],
        [188, 145],
        [172, 145],
        [164, 145],
        [156, 145],
        [148, 145],
        [140, 145],
        [148, 169],
        [164, 169],
        [172, 169],
        [156, 169],
        [140, 169],
        [132, 169],
        [124, 169],
        [116, 161],
        [104, 153],
        [104, 161],
        [104, 169],
        [ 90

# RecInitPopulation

In [48]:
obj = RecInitPopulation(method="rec_tsp", dataset=dataset)
obj.setParameters(GENOME_LENGTH=dataset["GENOME_LENGTH"])

In [21]:

city = 0
visited_city = np.zeros(obj.GENOME_LENGTH, dtype=bool)
visited_city[city] = True
for _ in range(10):
    args = obj.computeBestKDistance(city, 3, visited_city)
    print(args)
    visited_city[args] = True
    print("visited_city", np.argwhere(visited_city).reshape(-1))
    
    

[279   1   2]
visited_city [  0   1   2 279]
[  4   3 278]
visited_city [  0   1   2   3   4 278 279]
[241 242 276]
visited_city [  0   1   2   3   4 241 242 276 278 279]
[277   5 240]
visited_city [  0   1   2   3   4   5 240 241 242 276 277 278 279]
[243 247 275]
visited_city [  0   1   2   3   4   5 240 241 242 243 247 275 276 277 278 279]
[  6 239 246]
visited_city [  0   1   2   3   4   5   6 239 240 241 242 243 246 247 275 276 277 278
 279]
[244 274 248]
visited_city [  0   1   2   3   4   5   6 239 240 241 242 243 244 246 247 248 274 275
 276 277 278 279]
[  8 249   7]
visited_city [  0   1   2   3   4   5   6   7   8 239 240 241 242 243 244 246 247 248
 249 274 275 276 277 278 279]
[238 259 245]
visited_city [  0   1   2   3   4   5   6   7   8 238 239 240 241 242 243 244 245 246
 247 248 249 259 274 275 276 277 278 279]
[273 258 250]
visited_city [  0   1   2   3   4   5   6   7   8 238 239 240 241 242 243 244 245 246
 247 248 249 250 258 259 273 274 275 276 277 278 279]


In [27]:

city = 0
visited_city = np.zeros(obj.GENOME_LENGTH, dtype=bool)
visited_city[city] = True
#args = obj.computeBestKDistance(city, 3, visited_city)
#print(args)
population = obj.recFill(city, 3, visited_city, 2)
for tmp in population:
    tmp.insert(0, city)
population = np.array(population, dtype=np.int32)
#print(visited_city, args)
for individ in population:
    print("individ", individ)

visited_city [0] actual city 0
args [279   1   2] deep 2
visited_city [  0 279] actual city 279
args [  1   2 278] deep 1
visited_city [0 1] actual city 1
args [279   2 241] deep 1
visited_city [0 2] actual city 2
args [279 278   3] deep 1
individ [  0 279   1]
individ [  0 279   2]
individ [  0 279 278]
individ [  0   1 279]
individ [0 1 2]
individ [  0   1 241]
individ [  0   2 279]
individ [  0   2 278]
individ [0 2 3]


In [49]:

obj(5, window_size=6)

99
98
97
96
95
94
93
92
91
90
89
88
87
86
85
84
83
82
81
80
79
78
77
76
75
74
73
72
71
70
69
68
67
66
65
64
63
62
61
60
59
58
57
56
55
54
53
52
51
50
49
48
47
46
45
44
43
42
41
40
39
38
37
36
35
34
33
32
31
30
29
28
27
26
25
24
23
22
21
20
19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
individ [  0 279   1   2 278 277   3 276 275 274 273 272 271 270  15  16  17 132
 131  18  19  20 127 126 125 124  29  30  31  28  27  26  25  21  24  22
  23  13  12  11  10   9   7   6   8   5   4 259 258 257 256 253 252 251
 254 255 248 249 250 229 228 227 226 225 224 223 222 221 218 219 220 216
 215 212 211 206 207 208 209 210 213 214 217 204 203 202 201 199 198 197
 200 195 196 193 194 191 190 189 188 187 186 184 183 182 181 180 179 178
 175 176 150 151 155 152 154 153 128 129 130 133 134 135 267 266 136 137
 265 139 138 147 146 141 142 145 144 143 140 148 149 177 157 156 118 119
 120 121 122 123  33  32  35  34  37  36  38  39  40  41  42  59  60 117
  61  62  63  64  65  66  69  70  71  72  73 

In [ ]:

data = {"y":obj.fitness_values}
sns.lineplot(data=data)

In [ ]:

tmp = []
for _ in range(100000):
    arg = obj.selectParentChoice()
    tmp.append(arg)

data = {"y":np.array(tmp)}
sns.histplot(data=data, binwidth=3)

In [ ]:

tmp = []
for _ in range(100000):
    arg = obj.selectParentWheel()
    tmp.append(arg)

data = {"y":np.array(tmp)}
sns.histplot(data=data, binwidth=3)

In [ ]:

tmp = []
for _ in range(100000):
    arg = obj.selectParentTour()
    tmp.append(arg)

data = {"y":np.array(tmp)}
sns.histplot(data=data, binwidth=3)

In [ ]:

tmp = []
for _ in range(100000):
    arg = obj.selectParentTourChoice()
    tmp.append(arg)

data = {"y":np.array(tmp)}
sns.histplot(data=data, binwidth=3)

In [ ]:

tmp = []
for _ in range(10000):
    arg = obj.selectParentRise()
    tmp.append(arg)

data = {"y":np.array(tmp)}
sns.histplot(data=data, binwidth=3)