Description ????????????????????????

In [1]:
import numpy as np
import cv2 as cv
import yaml
from pathlib import Path
import sys
import pandas as pd

In [2]:
LCL_PATH = str(Path().cwd())
LCL_PATH

'/home/gheorghe/Desktop/Proiecte/master/MIN_metode_inspirate_din_natura/laborator_1/TTP'

In [ ]:

# adding local_folder to the system path
sys.path.append(LCL_PATH)
sys.path.append("/home/gheorghe/Desktop/AI/manager/imshow")
sys.path.append("C:/Users/Matei/MLProjects/UAIC-MIAO1/Sem-1/Metode-inspirate-din-natura/Homeworks/MIN")


def remove_modules(modules_name, *arg):
    if (modules_name in sys.modules):
        del sys.modules[modules_name]
        for key in arg:
            tmp_modules = "{}.{}".format(modules_name, key)
            del sys.modules[tmp_modules]

In [107]:

remove_modules("imshow")
remove_modules("builds.ttp_generator")
remove_modules("builds.genetic_optimizer_TSP")
remove_modules("builds.test_genetic_optimizer_TSP")

from imshow import *
from builds.ttp_generator import *
from builds.genetic_optimizer_TSP import *
from builds.test_genetic_optimizer_TSP import *

# Test methods GA

### init

In [5]:
map_generator = TTPGenerator(nbr_city=9, max_distance=300)
map_of_distance = map_generator()
map_of_distance

array([[  0.        , 190.19200824, 308.14606926, 111.57060545,
        254.09447062, 223.63586474, 310.83114387, 244.65894629,
        247.55201474],
       [190.19200824,   0.        , 131.01526629,  80.13114251,
         66.21933252,  59.46427499, 140.54536634,  60.30754513,
        104.00480758],
       [308.14606926, 131.01526629,   0.        , 206.48002325,
         69.64194139, 149.68299837,  19.23538406,  71.02112362,
         76.02631123],
       [111.57060545,  80.13114251, 206.48002325,   0.        ,
        145.8903698 , 114.00438588, 212.80977421, 138.22445514,
        159.65587994],
       [254.09447062,  66.21933252,  69.64194139, 145.8903698 ,
          0.        ,  81.39410298,  83.5463943 ,  13.92838828,
         81.05553652],
       [223.63586474,  59.46427499, 149.68299837, 114.00438588,
         81.39410298,   0.        , 164.75739741,  86.14522622,
        150.28306625],
       [310.83114387, 140.54536634,  19.23538406, 212.80977421,
         83.5463943 , 164.7573

In [108]:
tsp = TSP()
tsp.setParameters(
    POPULATION_SIZE = 20,  # numarul populatiei
    MUTATION_RATE   = 0.01,   # threshold-ul pentru a face o mutatie genetica
    CROSSOVER_RATE  = 0.5,   # threshold-ul pentru incrucisarea parintilor
    SELECT_RATE     = 0.7,   # threshold-ul de selectie, selectare dupa compatibilitate sau dupa probabilitate
    K_DISTANCE      = 1.0,   # coeficientul de inhibare a distantei
    K_NBR_CITY      = 0.9,   # coeficientul de inhibare a numarului de orase
    GENERATIONS     = 100,   # numarul de generatii
    K_BEST          = 15,     # salveaza pentru urmatoarea generatie numarul de indivizi, cu cel mai mare scor
    K_WRONG         = 5,     # salveaza pentru urmatoarea generatie numarul de indivizi, cu cel mai mic scor
    )
tsp.setMap(map_of_distance)
test_tsp = TestTSP(tsp)

### test

In [59]:
test_tsp.initPopulation()

+++start
result [[2 1 0 3 2]
 [0 2 1 3 0]
 [1 0 3 2 1]
 [2 3 1 0 2]
 [1 0 2 3 1]
 [2 3 1 0 2]
 [3 2 0 1 3]
 [2 0 1 3 2]
 [2 1 3 0 2]
 [2 0 1 3 2]
 [1 3 0 2 1]
 [3 0 1 2 3]
 [0 2 3 1 0]
 [3 2 0 1 3]
 [1 3 2 0 1]
 [0 3 1 2 0]
 [3 2 0 1 3]
 [2 3 1 0 2]
 [2 0 3 1 2]
 [2 1 0 3 2]]


In [60]:
test_tsp.selectValidPopulation()

arg_parents1 [10  5  8 14  3]
fitness_values_parents1 [0.5932179  0.45362381 0.29291371 0.86672265 0.45733242]
mask (5,)
arg_populations (20,)
result [ 0  1  2  3  4  6  7  9 11 12 13 15 16 17 18 19]


In [61]:
test_tsp.selectParent1()

fitness_values [0.88118264 0.55213899 0.00791789 0.7868154  0.83176428 0.95461425
 0.43246262 0.29980886 0.36614505 0.1064989  0.51711317 0.93573864
 0.18134997 0.02235853 0.56185183 0.05420489 0.53881292 0.44133682
 0.70535028 0.62229962]
fitness_values [ 2 13 15  9 12  7  8  6 17 10 16  1 14 19 18  3  4  0 11  5]
result [11  5  4]


In [108]:
test_tsp.selectParent2()

fitness_values [0.4796234  0.6338932  0.64600464 0.79850003 0.04922197 0.56189541
 0.18739864 0.09500487 0.21450968 0.68794129 0.12481678 0.28954533
 0.75654125 0.43757147 0.15418666 0.96582128 0.87609303 0.28268094
 0.59692721 0.09757471]
argsort fitness_values [ 4  7 19 10 14  6  8 17 11 13  0  5 18  1  2  9 12  3 16 15]
fitness_partener 0.1129462014969107
result [ 5 12 16 16 15]
result [10  5  8  9  1]
result [ 0  2  5 11 14]
result [ 0  2  3 15  8]
result [18  1 16 14  5]
result [ 1 15 12  5 13]
result [11 16  0 10 13]
result [16 16  3 15 15]
result [18 15  5 15  1]
result [15  9  2 18  5]
result [ 5 16 18 12  9]
result [16 16  8 12 15]
result [ 9 13 15 16 13]
result [11  1 15 13 12]
result [12 12  5 16  6]
result [14  5 12 15 11]
result [15 15 13  3  1]
result [15 16 13 15  0]
result [ 6 10  5  2 16]
result [15  0 17  5 12]


In [27]:
test_tsp.crossover()

parent1 [0 8 4 3 1 6 7 5 2 0]
parent2 [2 7 5 4 8 3 6 0 1 2]
childs [[0 8 4 3 1 3 6 0 1 0]
 [2 7 5 4 8 3 7 5 2 2]
 [0 7 5 4 8 6 7 5 2 0]
 [0 7 4 3 1 6 6 5 1 0]
 [0 8 4 3 1 3 6 0 1 0]]
childs [[0 7 5 4 8 6 7 5 2 0]
 [0 7 4 4 1 3 7 0 2 0]
 [0 7 5 4 8 6 7 5 2 0]
 [2 7 5 4 8 6 7 5 2 2]
 [0 8 4 3 8 3 6 5 1 0]]
childs [[2 7 5 4 8 6 7 5 2 2]
 [2 8 4 3 1 3 6 0 1 2]
 [2 7 5 4 8 6 7 5 2 2]
 [2 7 4 4 1 3 6 0 1 2]
 [0 8 4 3 1 3 6 0 1 0]]
childs [[2 8 4 4 8 6 6 0 1 2]
 [2 7 5 4 8 3 7 5 2 2]
 [0 8 4 3 1 3 6 0 1 0]
 [2 8 4 3 1 6 7 5 2 2]
 [0 8 4 3 1 3 6 0 1 0]]
childs [[2 8 4 3 1 3 6 0 1 2]
 [2 7 5 4 8 3 7 5 2 2]
 [0 8 4 4 8 6 7 0 1 0]
 [2 7 5 4 8 6 7 5 2 2]
 [0 8 5 3 1 6 6 0 1 0]]
childs [[2 8 4 3 1 3 6 0 1 2]
 [0 7 5 4 8 6 7 5 2 0]
 [0 8 4 3 1 6 6 5 2 0]
 [2 7 5 4 1 6 7 5 2 2]
 [2 7 5 3 1 6 7 5 2 2]]
childs [[2 7 5 4 1 6 7 0 2 2]
 [0 7 5 4 8 3 6 0 1 0]
 [0 8 4 3 1 3 6 0 1 0]
 [2 7 4 3 1 6 7 5 2 2]
 [0 7 5 4 8 3 6 5 2 0]]
childs [[2 8 4 3 1 6 7 5 2 2]
 [2 7 5 4 1 6 7 5 2 2]
 [0 8 4 3 1 3 7 5 2 0]
 [2

In [93]:
test_tsp.mutate()

parent1 [7 8 5 1 3 2 6 0 4 7]
parent2 [1 5 2 4 8 0 3 7 6 1]
Operatia de mutatie a fost aplicata: [[False False False False False  True  True False False False]
 [False False False False False False False False False False]
 [False False False False  True False False False False False]
 [False False False False False False False False False False]
 [False False False  True False False  True False False False]]
Operatia de mutatie a fost aplicata: [[False False False False False False False False False  True]
 [False False False False False False False False False False]
 [False  True False False False  True False False False False]
 [False False False False False  True False False False False]
 [False False False False False False False False False False]]
Operatia de mutatie a fost aplicata: [[False False False False False False  True False  True False]
 [False False False False False False False False False False]
 [False  True False False False  True False False False False]
 [False 

In [151]:
test_tsp.getIndividDistance()

individ [0 7 8 3 4 5 2 1 6 0]
distance 1770.4375977600193


In [152]:
test_tsp.getIndividNumberCities()

individ [7 1 2 5 8 3 0 4 6 7]
number_city 9


In [153]:
test_tsp.getDistances()

population [[1 4 0 5 7 8 2 6 3 1]
 [5 4 7 6 2 3 8 0 1 5]
 [3 5 8 4 7 1 6 0 2 3]
 [3 5 6 1 2 8 7 0 4 3]
 [3 0 5 2 1 6 7 8 4 3]
 [5 0 1 6 7 4 2 3 8 5]
 [2 1 3 5 4 8 7 0 6 2]
 [7 4 8 5 1 6 3 2 0 7]
 [1 7 4 6 0 8 5 3 2 1]
 [8 1 4 5 0 2 3 6 7 8]
 [6 7 3 1 5 8 0 2 4 6]
 [7 8 6 5 4 0 3 1 2 7]
 [5 2 0 1 4 6 7 3 8 5]
 [6 3 0 7 2 8 5 1 4 6]
 [4 6 5 7 8 2 0 3 1 4]
 [0 7 6 5 1 8 4 2 3 0]
 [3 7 8 0 6 5 4 2 1 3]
 [5 6 1 8 4 2 3 0 7 5]
 [8 2 7 6 0 5 3 4 1 8]
 [6 4 0 2 5 1 3 8 7 6]]
distances [1681.63443212  888.96837    1400.00793534 1778.55784112 1611.89820958
 1130.74084771 1866.43932721 1280.24174212 1309.13827493 1142.05601493
 1269.6887827  1632.84752191 1262.07013068 1428.43983925 1324.35850543
 1191.26913929 1640.47828287 1385.43302769 1559.1518716  1343.33115261]


In [154]:
test_tsp.getNumberCities()

population [[3 6 8 0 2 4 7 5 1 3]
 [4 8 0 1 6 2 3 7 5 4]
 [6 8 0 7 5 1 2 4 3 6]
 [6 3 4 1 7 2 5 8 0 6]
 [6 0 2 1 3 8 7 5 4 6]
 [7 2 3 1 4 0 6 5 8 7]
 [4 8 3 5 0 6 1 2 7 4]
 [2 7 1 3 8 4 0 5 6 2]
 [8 3 7 1 0 2 4 5 6 8]
 [7 3 6 0 5 2 1 4 8 7]
 [3 6 5 2 1 7 0 4 8 3]
 [7 6 8 4 3 2 1 5 0 7]
 [5 4 0 3 2 8 1 6 7 5]
 [8 5 2 7 6 3 1 0 4 8]
 [4 5 8 3 1 0 6 7 2 4]
 [6 1 7 8 2 3 5 0 4 6]
 [3 8 1 7 4 6 2 5 0 3]
 [1 5 8 4 0 7 3 6 2 1]
 [7 4 2 6 3 8 1 5 0 7]
 [7 5 8 1 6 4 2 0 3 7]]
GENOME_LENGTH 9
number_city [9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9]


In [155]:
test_tsp.distanceNorm()

population [[8 6 1 0 4 2 3 5 7 8]
 [2 5 3 0 6 7 1 4 8 2]
 [5 8 7 6 0 3 4 1 2 5]
 [8 4 7 0 5 1 6 2 3 8]
 [2 6 7 1 3 5 8 0 4 2]
 [4 2 3 7 8 0 6 1 5 4]
 [8 5 3 0 7 2 4 6 1 8]
 [4 5 3 7 8 1 2 0 6 4]
 [1 7 8 3 6 0 4 2 5 1]
 [0 1 6 5 4 8 2 7 3 0]
 [8 6 5 7 4 0 2 3 1 8]
 [3 5 0 2 1 6 4 7 8 3]
 [4 8 3 7 1 6 5 0 2 4]
 [2 5 6 8 4 7 3 0 1 2]
 [8 0 6 2 1 5 3 4 7 8]
 [4 3 8 7 0 1 6 5 2 4]
 [1 6 2 3 4 5 7 0 8 1]
 [6 4 2 8 7 5 0 3 1 6]
 [2 6 4 3 1 8 7 5 0 2]
 [4 8 7 2 5 0 6 1 3 4]]
distances [1503.81843534 1554.35196084 1625.63729215 1297.94862853 1658.80209979
 1310.22597728 1649.9284378  1538.87044374 1750.6927554  1395.41328032
 1253.1665652  1442.17580479 1558.43868523 1519.57926701 1630.61462347
 1709.89175672 1356.76759289 1505.87783669 1556.87644577 1874.52568478]
arg distance [19  8 15  4  6 14  2 12 18  1  7 13 17  0 11  9 16  5  3 10]
norm distances [0.90908479 0.89272185 0.87061615 0.98244608 0.86070058 0.97774067
 0.86333142 0.89767189 0.83437101 0.94629321 1.         0.92987561
 0.891424

In [163]:
test_tsp.getKBest()

parent1 [8 5 3 1 0 6 7 2 4 8]
parent2 [6 1 8 5 3 2 7 4 0 6]
fitness_values [1.50271127 1.68520068 1.79298613 1.74634442 1.77787484 1.66278461
 1.6829178  1.5940118  1.67659258 1.74634442 1.65363561 1.77779312
 1.55206364 1.79298613 1.58127341 1.65363561 1.66147245 1.82640675
 1.81620287 1.72578825 1.85274135 1.72847169 1.82541805 1.78430029
 1.87160491]
argsort fitness_values [ 0 12 14  7 10 15 16  5  8  6  1 19 21  9  3 11  4 23  2 13 18 22 17 20
 24]
k_best [18 22 17 20 24]


In [103]:
test_tsp.getKExtreme()

fitness_values [0.27095158 0.48318808 0.16995079 0.56128001 0.72580376 0.97282165
 0.15208856 0.62946978 0.81907158 0.49415273 0.69258259 0.72871755
 0.94508031 0.25932089 0.58641014 0.93985172 0.92613458 0.75923148
 0.48808997 0.96433633]
sort fitness_values [0.15208856 0.16995079 0.25932089 0.27095158 0.48318808 0.48808997
 0.49415273 0.56128001 0.58641014 0.62946978 0.69258259 0.72580376
 0.72871755 0.75923148 0.81907158 0.92613458 0.93985172 0.94508031
 0.96433633 0.97282165]
arg sort fitness_values [ 6  2 13  0  1 18  9  3 14  7 10  4 11 17  8 16 15 12 19  5]
arg_extreme [18  9  3 14  7 10  4 11 17  8 16 15 12 19  5]
extreme fitness [0.48808997 0.49415273 0.56128001 0.58641014 0.62946978 0.69258259
 0.72580376 0.72871755 0.75923148 0.81907158 0.92613458 0.93985172
 0.94508031 0.96433633 0.97282165]


In [109]:
test_tsp.getKWeaks()

fitness_values [0.08972636 0.805041   0.25282856 0.19288404 0.29664141 0.53217379
 0.68928284 0.83240104 0.61711253 0.98334894 0.1448928  0.86925045
 0.98373475 0.35182599 0.67418031 0.64666247 0.84799916 0.44264535
 0.17803758 0.07054364]
sort fitness_values [0.98373475 0.98334894 0.86925045 0.84799916 0.83240104 0.805041
 0.68928284 0.67418031 0.64666247 0.61711253 0.53217379 0.44264535
 0.35182599 0.29664141 0.25282856 0.19288404 0.17803758 0.1448928
 0.08972636 0.07054364]
arg sort fitness_values [12  9 11 16  7  1  6 14 15  8  5 17 13  4  2  3 18 10  0 19]
arg_extreme [19  0 10 18  3  2  4 13 17  5]
extreme fitness [0.07054364 0.08972636 0.1448928  0.17803758 0.19288404 0.25282856
 0.29664141 0.35182599 0.44264535 0.53217379]


In [23]:
test_tsp.permuteSimilarIndivids()

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
[[4 8 3 7 9 5 6 0 1 2]
 [4 2 3 9 8 6 5 7 1 0]
 [6 3 2 5 9 8 7 4 1 0]
 [3 1 5 7 4 9 6 8 0 2]]
population shape (10, 10)
False [6 3 2 5 9 8 7 4 1 0]
False [4 8 3 7 9 5 6 0 1 2]
False [4 2 3 9 8 6 5 7 1 0]
False [3 1 5 7 4 9 6 8 0 2]
True [3 1 5 7 4 9 6 8 0 2]
True [3 1 5 7 4 9 6 8 0 2]
True [6 3 2 5 9 8 7 4 1 0]
True [3 1 5 7 4 9 6 8 0 2]
True [6 3 2 5 9 8 7 4 1 0]
True [4 2 3 9 8 6 5 7 1 0]
similar size 6, population size 10
actual flag:   prev flag:    individ
False False [6 3 2 5 9 8 7 4 1 0]
False False [4 8 3 7 9 5 6 0 1 2]
False False [4 2 3 9 8 6 5 7 1 0]
False False [3 1 5 7 4 9 6 8 0 2]
False True [3 1 8 4 9 0 7 6 5 2]
False True [3 1 0 6 5 9 7 8 4 2]
False True [6 9 3 1 2 5 4 8 7 0]
False True [3 1 5 4 7 9 6 0 8 2]
False True [6 7 9 1 5 8 4 2 3 0]
False True [4 6 8 5 9 3 7 2 1 0]
