In [1]:

import sys
from pathlib import Path
import seaborn as sns

In [3]:

LCL_PATH  = str(Path().cwd().parent.parent)
ROOT_PATH = str(Path(LCL_PATH).parent.parent)
print("""
root path:\t{}
local path:\t{}""".format(ROOT_PATH, LCL_PATH))


root path:	/home/gheorghe/Desktop/Proiecte/master/MIN_metode_inspirate_din_natura
local path:	/home/gheorghe/Desktop/Proiecte/master/MIN_metode_inspirate_din_natura/laborator_1/TTP


In [4]:

# adding local_folder to the system path
sys.path.append(LCL_PATH)
sys.path.append(ROOT_PATH)

from sys_function import * # este in root

In [129]:

sys_remove_modules("imshow")
sys_remove_modules("builds.dataset_utils.dataset_ttp_man")
sys_remove_modules("builds.dataset_utils.ttp_generator")

from imshow import *
from builds.dataset_utils.dataset_ttp_man import *
from builds.dataset_utils.ttp_generator import *

# Data aquisition

In [6]:

ttp_generator = TTPGenerator("{}/data".format(LCL_PATH))
dataset = ttp_generator(nodes_file="NODE_COORD_SECTION.csv",
                        items_file="ITEMS_SECTION.csv")
dataset

{'GENOME_LENGTH': 280,
 'distance': array([[ 0., 20., 24., ..., 43., 34., 18.],
        [20.,  0., 18., ..., 36., 28.,  9.],
        [24., 18.,  0., ..., 20., 11., 10.],
        ...,
        [43., 36., 20., ...,  0.,  9., 29.],
        [34., 28., 11., ...,  9.,  0., 20.],
        [18.,  9., 10., ..., 29., 20.,  0.]], shape=(280, 280)),
 'coords': array([[288, 149],
        [288, 129],
        [270, 133],
        [256, 141],
        [256, 157],
        [246, 157],
        [236, 169],
        [228, 169],
        [228, 161],
        [220, 169],
        [212, 169],
        [204, 169],
        [196, 169],
        [188, 169],
        [196, 161],
        [188, 145],
        [172, 145],
        [164, 145],
        [156, 145],
        [148, 145],
        [140, 145],
        [148, 169],
        [164, 169],
        [172, 169],
        [156, 169],
        [140, 169],
        [132, 169],
        [124, 169],
        [116, 161],
        [104, 153],
        [104, 161],
        [104, 169],
        [ 90

# DatasetTTPMan

In [130]:

dataset_obj = DatasetTTPMan(dataset)
#route  = np.arange(dataset_obj.GENOME_LENGTH, dtype=np.int32)[::-1]
#profit = np.random.randint(low=0, high=2, size=dataset_obj.GENOME_LENGTH)

### individDistanceFromCityToStart

In [110]:
dataset_obj.individDistanceFromCityToStart(route)

array([2808., 2788., 2779., 2762., 2751., 2743., 2735., 2727., 2719.,
       2711., 2685., 2677., 2669., 2661., 2653., 2645., 2634., 2623.,
       2612., 2601., 2593., 2585., 2577., 2569., 2561., 2553., 2545.,
       2537., 2529., 2505., 2497., 2486., 2475., 2461., 2447., 2439.,
       2431., 2422., 2414., 2405., 2397., 2389., 2381., 2373., 2365.,
       2357., 2349., 2341., 2333., 2325., 2309., 2301., 2293., 2285.,
       2277., 2269., 2261., 2250., 2234., 2226., 2218., 2210., 2202.,
       2194., 2186., 2178., 2170., 2162., 2154., 2146., 2138., 2130.,
       2122., 2114., 2105., 2094., 2083., 2072., 2061., 2052., 2044.,
       2036., 2028., 2020., 2012., 2004., 1996., 1980., 1963., 1949.,
       1937., 1929., 1921., 1908., 1900., 1889., 1881., 1873., 1865.,
       1857., 1849., 1840., 1822., 1813., 1805., 1782., 1764., 1753.,
       1737., 1737., 1729., 1720., 1706., 1698., 1686., 1672., 1664.,
       1656., 1648., 1640., 1624., 1616., 1608., 1600., 1577., 1561.,
       1553., 1537.,

In [14]:
dataset_obj.individCityDistance(route)

array([20., 18., 16., 16., 10., 16.,  8.,  8., 11.,  8.,  8.,  8.,  8.,
       11., 18., 16.,  8.,  8.,  8.,  8., 25., 16.,  8., 16., 16.,  8.,
        8., 11., 14.,  8.,  8., 15., 13., 16.,  8.,  9.,  8.,  8.,  8.,
        8.,  8.,  8., 16.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,
        8.,  8.,  8.,  8.,  8.,  8., 16.,  8., 10.,  8.,  8.,  8.,  8.,
       11., 12.,  8., 12.,  8.,  8.,  8.,  8.,  8.,  8., 11.,  8., 16.,
        9.,  8.,  8.,  8.,  8.,  8.,  8., 10., 10., 12.,  9.,  8.,  8.,
       12.,  8.,  8.,  8.,  8.,  8., 13., 12.,  8.,  8.,  8.,  8.,  8.,
        8.,  8., 16.,  8., 10.,  8.,  8., 10.,  8.,  8.,  8., 10.,  8.,
       48.,  8.,  8.,  8.,  8.,  8.,  8., 12.,  8.,  8.,  8.,  8.,  8.,
        8.,  8., 14.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,
        8.,  8.,  8.,  8.,  9., 16., 24.,  8., 16., 16.,  8., 16., 23.,
        8.,  8.,  8., 16.,  8.,  8.,  8.,  8., 14., 12.,  8., 14.,  9.,
        8.,  0., 16., 11., 18., 23.,  8.,  9., 18.,  9.,  8.,  8

### neighborsDistance

In [19]:
for city, distances in enumerate(dataset_obj.neighborsDistance(4)):
    print("city {}, distances {}".format(city, distances))

city 0, distances [18. 20. 24. 33.]
city 1, distances [ 9. 18. 20. 20.]
city 2, distances [10. 11. 16. 18.]
city 3, distances [10. 13. 16. 16.]
city 4, distances [10. 16. 19. 23.]
city 5, distances [10. 16. 16. 16.]
city 6, distances [ 8. 11. 16. 16.]
city 7, distances [ 8.  8.  8. 16.]
city 8, distances [ 8. 11. 11. 16.]
city 9, distances [ 8.  8. 11. 16.]
city 10, distances [ 8.  8. 16. 16.]
city 11, distances [ 8.  8. 11. 16.]
city 12, distances [ 8.  8.  8. 16.]
city 13, distances [ 8. 11. 16. 16.]
city 14, distances [ 8. 11. 11. 16.]
city 15, distances [ 8. 16. 16. 18.]
city 16, distances [ 8. 11. 16. 16.]
city 17, distances [ 8.  8.  8. 11.]
city 18, distances [ 8.  8.  8. 11.]
city 19, distances [ 8.  8.  8. 11.]
city 20, distances [ 8.  8.  8. 11.]
city 21, distances [ 8.  8. 16. 16.]
city 22, distances [ 8.  8. 16. 24.]
city 23, distances [ 8. 16. 16. 24.]
city 24, distances [ 8.  8. 16. 16.]
city 25, distances [ 8.  8. 16. 16.]
city 26, distances [ 8.  8. 16. 18.]
city 27, di

### calculateIndividProportions

In [53]:
proportions = dataset_obj.calculateIndividProportions(profit)
proportions

array([  0.        ,   0.        , 100.99999495, 100.99999748,
       100.99999495,   1.11160714,   0.        ,   1.11160714,
         0.        ,   1.27247956,   1.27247956,   1.14492754,
         1.14492754,   1.16313214,   1.16313214,   0.        ,
         0.        ,   1.11441648,   1.81967213,   0.        ,
         1.81967213,   1.81967213,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   1.21598272,
         1.21598272,   0.        ,   1.16977929,   0.        ,
         0.        ,   1.30769231,   1.30769231,   1.30769231,
         1.30769231,   0.        ,   0.        ,   0.        ,
         1.12886598,   0.        ,   0.        ,   1.81300813,
         1.28089888,   0.        ,   1.32786885,   0.        ,
         1.32786885,   0.        ,   0.        ,   3.12765957,
         0.        ,   1.15503876,   1.15503876,   0.        ,
         1.71942446,   0.        ,   1.4048583 ,   1.4048583 ,
         1.4048583 ,   0.        ,   1.47393365,   0.  

### calculateProportions

In [43]:
proportions = dataset_obj.calculateProportions()
proportions

array([  0.        , 100.9999899 , 100.99999495, 100.99999748,
       100.99999495,   1.11160714,   1.11160714,   1.11160714,
         1.27247956,   1.27247956,   1.27247956,   1.14492754,
         1.14492754,   1.16313214,   1.16313214,   1.16313214,
         1.11441648,   1.11441648,   1.81967213,   1.81967213,
         1.81967213,   1.81967213,   1.20576132,   1.20576132,
         1.20576132,   1.12150668,   1.12150668,   1.21598272,
         1.21598272,   1.21598272,   1.16977929,   1.16977929,
         1.16977929,   1.30769231,   1.30769231,   1.30769231,
         1.30769231,   1.1       ,   1.1       ,   1.1       ,
         1.12886598,   1.12886598,   1.12886598,   1.81300813,
         1.28089888,   1.32786885,   1.32786885,   1.32786885,
         1.32786885,   3.12765957,   3.12765957,   3.12765957,
         1.15503876,   1.15503876,   1.15503876,   1.15503876,
         1.71942446,   1.4048583 ,   1.4048583 ,   1.4048583 ,
         1.4048583 ,   1.47393365,   1.47393365,   1.47

### argminIndividProportion

In [36]:
profit

array([1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1])

In [38]:
#profit[0] = 0
dataset_obj.argminIndividProportion(profit)

[         inf          inf 100.99999495 100.99999748 100.99999495
   1.11160714          inf   1.11160714          inf   1.27247956
   1.27247956   1.14492754   1.14492754   1.16313214   1.16313214
          inf          inf   1.11441648   1.81967213          inf
   1.81967213   1.81967213          inf          inf          inf
          inf          inf   1.21598272   1.21598272          inf
   1.16977929          inf          inf   1.30769231   1.30769231
   1.30769231   1.30769231          inf          inf          inf
   1.12886598          inf          inf   1.81300813   1.28089888
          inf   1.32786885          inf   1.32786885          inf
          inf   3.12765957          inf   1.15503876   1.15503876
          inf   1.71942446          inf   1.4048583    1.4048583
   1.4048583           inf   1.47393365          inf          inf
   2.                  inf          inf   2.           1.15948963
          inf   1.15948963   1.13157895   1.13157895          inf
   1.128865

np.int64(258)

### argsortIndividProportions

In [68]:

argsortproportion, start_idx = dataset_obj.argsortIndividProportions(profit)
argsortproportion[start_idx:]

array([258, 259, 260, 169, 170, 179, 177,  83,  80,  81, 197, 269, 184,
       162,   5,   7, 145, 146, 114,  17, 190, 191, 192, 237, 238, 239,
       254, 252, 253, 271,  40,  75, 137, 138,  72,  73, 200,  92,  95,
        93, 226, 230, 231, 232, 228, 134, 135, 136, 120, 174,  11,  12,
       264, 267, 265, 262, 263,  53,  54, 202,  69,  71, 109,  13,  14,
       153, 155, 245, 246,  30, 218, 163, 165,  97,  98, 241,  77, 131,
       278,  27,  28, 206, 171, 172, 209, 139, 249, 119,   9,  10, 186,
       279,  44, 144,  33,  34,  36,  35,  48,  46,  88,  89,  91, 103,
       104,  58,  60,  59,  99, 101, 158,  62, 152, 151, 255, 256, 126,
       128, 223, 211,  56,  43,  18,  21,  20, 167, 214,  87,  86,  65,
        68, 181,  51, 220, 221,   4,   2,   3])

In [69]:
argsortproportion

array([  0,   1, 277, 276,  22,  23,  24,  25,  26,  29,  31,  32, 244,
       247, 248, 250, 251, 257,  37,  47,  42,  41,  39,  38,  49,  45,
       236, 235, 234, 233, 229,  50, 213,  79, 212,  67,  70,  74, 242,
       240,  57,  55, 243,  52,  61,  66,  64,  63,  82,  78,  76,  96,
        94,  90,  85,  84, 227, 225, 224, 222, 219, 217, 216, 215, 133,
       113, 115, 116, 118, 117, 121, 122, 127, 123, 124, 125, 130, 196,
       198, 199, 100, 201, 203, 204, 205, 207, 208, 210, 107, 102, 105,
       106, 110, 108, 111, 112, 132, 183, 185, 187, 189, 188, 193, 194,
       195, 140, 180, 182, 129,  15,   6,   8, 164, 166, 168, 161, 157,
       156, 160, 159, 150, 154, 148, 149, 147, 143, 142, 141, 274, 272,
       273, 173, 176, 175, 178, 275, 270, 266,  19, 268, 261,  16, 258,
       259, 260, 169, 170, 179, 177,  83,  80,  81, 197, 269, 184, 162,
         5,   7, 145, 146, 114,  17, 190, 191, 192, 237, 238, 239, 254,
       252, 253, 271,  40,  75, 137, 138,  72,  73, 200,  92,  9

In [70]:
proportions[argsortproportion[start_idx:]]

array([  1.10235415,   1.10235415,   1.10235415,   1.10427529,
         1.10427529,   1.10604454,   1.10638298,   1.10672359,
         1.10672359,   1.10672359,   1.10672359,   1.10718114,
         1.10845987,   1.10857763,   1.11160714,   1.11160714,
         1.11299435,   1.11299435,   1.11350738,   1.11441648,
         1.11614402,   1.11614402,   1.11614402,   1.12062726,
         1.12062726,   1.12062726,   1.12150668,   1.12150668,
         1.12150668,   1.12360939,   1.12886598,   1.12886598,
         1.12903226,   1.12903226,   1.13157895,   1.13157895,
         1.13262599,   1.13315579,   1.13315579,   1.13315579,
         1.13831259,   1.13831259,   1.13831259,   1.13831259,
         1.13831259,   1.13850415,   1.13850416,   1.13850416,
         1.14044944,   1.14104372,   1.14492754,   1.14492754,
         1.14513788,   1.14513788,   1.14513788,   1.14684288,
         1.14684288,   1.15503876,   1.15503876,   1.1572327 ,
         1.15948963,   1.15948963,   1.16313214,   1.16

### calculateIndividEarning

In [135]:
earn, start_arg = dataset_obj.calculateIndividEarning(route, profit)
earn, start_arg

(array([4.56160568e-04, 4.35650027e-04,           -inf,           -inf,
                  -inf,           -inf,           -inf,           -inf,
        4.13243617e-04,           -inf, 4.12357965e-04,           -inf,
        4.29051285e-04,           -inf, 4.31638854e-04, 4.32944378e-04,
        4.35399726e-04, 4.37225649e-04,           -inf, 4.23819356e-04,
        4.25126936e-04, 4.26442609e-04,           -inf, 6.14260289e-04,
        6.16179102e-04, 4.39289731e-04, 4.40670602e-04, 4.42060182e-04,
                  -inf,           -inf, 5.08718570e-04,           -inf,
                  -inf, 4.75209884e-04, 4.77928699e-04,           -inf,
                  -inf,           -inf, 4.99311851e-04,           -inf,
        4.67512416e-04, 4.69077966e-04, 4.70654037e-04,           -inf,
                  -inf,           -inf,           -inf, 4.86250571e-04,
        4.87917954e-04, 4.89596811e-04,           -inf, 4.94703427e-04,
                  -inf, 4.98167434e-04,           -inf,         

### argsortIndividEarning

In [136]:
arg_earn, start_arg = dataset_obj.argsortIndividEarning(route, profit)
earn[arg_earn[start_arg:]]

array([4.12357965e-04, 4.13243617e-04, 4.23819356e-04, 4.25126936e-04,
       4.26442609e-04, 4.29051285e-04, 4.31638854e-04, 4.32944378e-04,
       4.35399726e-04, 4.35650027e-04, 4.37225649e-04, 4.39289731e-04,
       4.40670602e-04, 4.42060182e-04, 4.56160568e-04, 4.67512416e-04,
       4.69077966e-04, 4.70654037e-04, 4.75209884e-04, 4.77928699e-04,
       4.86250571e-04, 4.87917954e-04, 4.89596811e-04, 4.94703427e-04,
       4.98167434e-04, 4.99311851e-04, 5.08718570e-04, 5.29442546e-04,
       5.45721689e-04, 5.51961986e-04, 5.58509992e-04, 5.63709100e-04,
       5.68590942e-04, 5.72675228e-04, 5.76095044e-04, 5.86797178e-04,
       5.87656808e-04, 5.98185256e-04, 6.07235444e-04, 6.14260289e-04,
       6.16179102e-04, 6.35737068e-04, 6.38678593e-04, 6.40316343e-04,
       6.69291567e-04, 6.69430938e-04, 7.03570427e-04, 7.12872439e-04,
       7.15973782e-04, 7.22568820e-04, 7.27625515e-04, 7.40868845e-04,
       7.52318202e-04, 7.64419197e-04, 7.68642507e-04, 7.93509683e-04,
      