In [2]:
import numpy as np

Set Cover, Graph Coloring, TSP, Knapsack Problem

In [ ]:

class GeneticAO(object):
    """Genetic algorithm optimization:

    """
    # constante pentru setarea algoritmului
    POPULATION_SIZE = 100   # numarul populatiei
    GENOME_LENGTH   = 20    # numarul de genomuri sau log2((b-a)*10^p), p - precizia in zecimale
    MUTATION_RATE   = 0.01  # threshold-ul pentru a face o mutatie genetica
    CROSSOVER_RATE  = 0.5   # threshold-ul pentru incrucisarea parintilor
    GENERATIONS     = 20    # numarul generatiilor

    def __init__(self, fitness_fn=None):
        if (fitness_fn is not None):
            self.fitness = fitness_fn
        else:
            self.fitness = self.__fitness

    def __call__(self):
        population = self.init_population()
        print("population", population, population.shape)
        # init fitness value
        fitness_values = self.fitness(population)
        # evolutia generatiilor
        for generation in range(GeneticAO.GENERATIONS):
            new_population = []
            # nasterea unei noi generatii
            for _ in range(GeneticAO.POPULATION_SIZE//2):
                # selectia
                parent1 = self.select_parent(population, fitness_values)
                parent2 = self.select_parent(population, fitness_values)
                # incrucisarea
                offspring1, offspring2 = self.crossover(parent1, parent2)
                # mutatia
                offspring1, offspring2 = self.mutate(offspring1), self.mutate(offspring2)
                # nasterea
                new_population.extend([offspring1, offspring2])
            # schimbarea generatiei
            population = np.array(new_population)
            # update fitness values
            fitness_values = self.fitness(population)
            best_fitness   = np.max(fitness_values)
            # printeaza metricile
            print("Generation {}: Best fitness {}".format(generation, best_fitness))
        #
        best_index    = np.argmax(fitness_values)
        best_solution = population[best_index]
        print("Best solution: {}".format(best_solution))
        print("Best Fitness: {}".format(self.fitness([best_solution])[0]))


    def random_genome(self, length):
        return np.random.randint(low=0, high=2, size=length)

    def init_population(self):
        size = (GeneticAO.POPULATION_SIZE, GeneticAO.GENOME_LENGTH)
        return np.random.randint(low=0, high=2, size=size)

    def __fitness(self, genome):
        return np.sum(genome, axis=1)

    def select_parent(self, population, fitness_values):
        total_fitness = np.sum(fitness_values, axis=None)
        pick = np.random.uniform(low=0, high=total_fitness, size=None)
        current = 0
        for individ, fitness_value in zip(population, fitness_values):
            current += fitness_value
            if (current > pick):
                return individ

    def crossover(self, parent1, parent2):
        size = parent1.shape[0]
        crossover_rate = np.random.random(size=None)
        if (crossover_rate < GeneticAO.CROSSOVER_RATE):
            crossover_point = np.random.randint(low=1, high=size, size=None)
            child1 = np.concatenate(
                (parent1[:crossover_point], parent2[crossover_point:]),
                axis=None)
            child2 = np.concatenate(
                (parent2[:crossover_point], parent1[crossover_point:]),
                axis=None)
            return child1, child2
        else:
            return parent1, parent2

    def mutate(self, genome):
        mutation_rate = np.random.random(size=genome.shape[0])
        mutation_arg  = mutation_rate < GeneticAO.MUTATION_RATE
        genome[mutation_arg] = np.abs(genome[mutation_arg] - 1)
        return genome


In [ ]:
full_genome = GeneticAO()
full_genome()

population [[1 0 0 ... 1 0 0]
 [1 1 0 ... 1 0 1]
 [0 0 1 ... 0 0 1]
 ...
 [0 1 0 ... 1 0 0]
 [1 0 1 ... 0 1 0]
 [1 0 0 ... 0 1 1]] (100, 20)
Generation 0: Best fitness 16
Generation 1: Best fitness 15
Generation 2: Best fitness 15
Generation 3: Best fitness 15
Generation 4: Best fitness 18
Generation 5: Best fitness 18
Generation 6: Best fitness 18
Generation 7: Best fitness 17
Generation 8: Best fitness 17
Generation 9: Best fitness 16
Generation 10: Best fitness 16
Generation 11: Best fitness 16
Generation 12: Best fitness 16
Generation 13: Best fitness 17
Generation 14: Best fitness 18
Generation 15: Best fitness 18
Generation 16: Best fitness 18
Generation 17: Best fitness 18
Generation 18: Best fitness 17
Generation 19: Best fitness 17
Best solution: [1 1 1 1 0 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1]
Best Fitness: 17


In [ ]:
empty_fitness_fn = lambda genome: 1./(np.sum(genome, axis=1)+0.1)
empty_genome = GeneticAO(fitness_fn=empty_fitness_fn)
empty_genome()

population [[0 1 0 ... 1 1 1]
 [1 1 0 ... 0 0 1]
 [0 0 1 ... 0 1 1]
 ...
 [1 0 0 ... 1 1 0]
 [0 0 1 ... 1 1 1]
 [1 0 0 ... 1 0 1]] (100, 20)
Generation 0: Best fitness 0.24390243902439027
Generation 1: Best fitness 0.24390243902439027
Generation 2: Best fitness 0.3225806451612903
Generation 3: Best fitness 0.3225806451612903
Generation 4: Best fitness 0.3225806451612903
Generation 5: Best fitness 0.47619047619047616
Generation 6: Best fitness 0.47619047619047616
Generation 7: Best fitness 0.47619047619047616
Generation 8: Best fitness 0.9090909090909091
Generation 9: Best fitness 0.9090909090909091
Generation 10: Best fitness 0.9090909090909091
Generation 11: Best fitness 0.9090909090909091
Generation 12: Best fitness 10.0
Generation 13: Best fitness 10.0
Generation 14: Best fitness 10.0
Generation 15: Best fitness 10.0
Generation 16: Best fitness 10.0
Generation 17: Best fitness 10.0
Generation 18: Best fitness 10.0
Generation 19: Best fitness 10.0
Best solution: [0 0 0 0 0 0 0 0 0 0 

In [14]:

arr1 = np.arange(0, 1.1, 0.1)
arr1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [9]:
2*arr1/(arr1+1)

array([0.        , 0.18181818, 0.33333333, 0.46153846, 0.57142857,
       0.66666667, 0.75      , 0.82352941, 0.88888889, 0.94736842,
       1.        ])

In [11]:

arr2 = np.arange(0, 1.1, 0.1).reshape(-1, 1)
arr2

array([[0. ],
       [0.1],
       [0.2],
       [0.3],
       [0.4],
       [0.5],
       [0.6],
       [0.7],
       [0.8],
       [0.9],
       [1. ]])

In [13]:
2*arr1*arr2/(arr1+arr2+1e-7)

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.09999995, 0.13333329, 0.14999996, 0.15999997,
        0.16666664, 0.17142855, 0.17499998, 0.17777776, 0.17999998,
        0.18181817],
       [0.        , 0.13333329, 0.19999995, 0.23999995, 0.26666662,
        0.28571424, 0.29999996, 0.31111108, 0.31999997, 0.3272727 ,
        0.33333331],
       [0.        , 0.14999996, 0.23999995, 0.29999995, 0.34285709,
        0.37499995, 0.39999996, 0.41999996, 0.4363636 , 0.44999996,
        0.46153843],
       [0.        , 0.15999997, 0.26666662, 0.34285709, 0.39999995,
        0.4444444 , 0.47999995, 0.50909086, 0.53333329, 0.55384611,
        0.57142853],
       [0.        , 0.16666664, 0.28571424, 0.37499995, 0.4444444 ,
        0.49999995, 0.5454545 , 0.58333328, 0.61538457, 0.6428571 ,
        0.66666662],
       [0.        , 0.17142855, 0.29999996, 0.39999996, 0.